/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 0a61dfcd-54d4-4d39-a3d9-fdc0dc18210f
-/

/-
We verified the formalization of Polya-Szego Problem 135, which corresponds to the Weierstrass Approximation Theorem.
The original formalization had a minor type error where the function `f` (defined on the subtype `Set.Icc a b`) was applied to a real number `x` instead of `⟨x, hx⟩`.
We corrected this by ensuring the argument to `f` is of the correct subtype.
We then proved the theorem using the Mathlib result `exists_polynomial_near_continuousMap`, which provides the existence of a polynomial approximation in the uniform norm.
The proof demonstrates that for any $\epsilon > 0$, there exists a polynomial $p$ such that $|f(x) - p(x)| < \epsilon$ for all $x \in [a, b]$.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check exists_polynomial_near_continuousMap

/-
Every function defined and continuous on the finite interval $[a, b]$ can be approximated uniformly on $[a, b]$ by polynomials to any degree of accuracy.
-/
theorem problem_135 (a b : ℝ) (hab : a ≤ b) (f : C(Set.Icc a b, ℝ)) (ε : ℝ) (hε : 0 < ε) :
    ∃ p : Polynomial ℝ, ∀ x (hx : x ∈ Set.Icc a b), ‖f ⟨x, hx⟩ - p.eval x‖ < ε := by
      have := @exists_polynomial_near_continuousMap;
      exact this a b f ε hε |> fun ⟨ p, hp ⟩ => ⟨ p, fun x hx => by simpa [ abs_sub_comm, ContinuousMap.norm_lt_iff ] using lt_of_le_of_lt ( ContinuousMap.norm_coe_le_norm ( p.toContinuousMapOn ( Set.Icc a b ) - f ) ⟨ x, hx ⟩ ) hp ⟩