/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 2b4fda5f-c3d6-41b3-a8a7-59ef366cdbcd
-/

/-
We formalized the problem as `problem_111`, which states that the set of points with respect to which the image of a circle under an analytic function is star-shaped is a convex set. The condition for star-shapedness is given by the positivity of the real part of a certain complex expression. We corrected the user's code to use valid Lean 4 syntax (e.g., `Complex.norm` instead of `Complex.abs`, `star` instead of `conj`) and provided a complete proof.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check Complex
#check (0 : ℂ)
#check (Complex.I : ℂ)

#check (star : ℂ → ℂ)
#check (norm : ℂ → ℝ)

/-
Polya-Szego Problem 111: If f is analytic on a neighborhood of the closed disk |z| ≤ r, and the image f(|z|=r) is star-shaped with respect to two points a and b, then it is star-shaped with respect to any convex combination λa + μb.
-/
theorem problem_111 {f : ℂ → ℂ} {r : ℝ} (hr : 0 < r)
    (hf : AnalyticOn ℂ f (Metric.closedBall (0 : ℂ) r)) :
    Convex ℝ {w : ℂ | ∀ z : ℂ, ‖z‖ = r →
      ∃ (t : ℝ) (ht : 0 ≤ t) (hz_diff : DifferentiableAt ℂ f z),
      t * (z * deriv f z * star (f z - w)).re > 0} := by
  refine' convex_iff_forall_pos.mpr _;
  intro w₁ hw₁ w₂ hw₂ a b ha hb hab z hz
  obtain ⟨t₁, ht₁, hz_diff₁, h₁⟩ := hw₁ z hz
  obtain ⟨t₂, ht₂, hz_diff₂, h₂⟩ := hw₂ z hz
  have hz_diff : DifferentiableAt ℂ f z := hz_diff₁
  use (a * t₁ + b * t₂);
  refine' ⟨ by positivity, hz_diff, _ ⟩;
  -- Since $a$ and $b$ are positive and $t₁$ and $t₂$ are non-negative, the product $(a * t₁ + b * t₂)$ is positive. Also, the real part of the expression is a linear combination of the positive terms from $h₁$ and $h₂$.
  have h_pos : (a * t₁ + b * t₂) * (a * (z * deriv f z * Star.star (f z - w₁)).re + b * (z * deriv f z * Star.star (f z - w₂)).re) > 0 := by
    by_cases ht₁_zero : t₁ = 0;
    · aesop;
    · by_cases ht₂_zero : t₂ = 0;
      · aesop;
      · exact mul_pos ( by positivity ) ( by nlinarith [ show 0 < a * ( z * deriv f z * Star.star ( f z - w₁ ) |> Complex.re ) from by nlinarith [ show 0 < t₁ from lt_of_le_of_ne ht₁ ( Ne.symm ht₁_zero ) ], show 0 < b * ( z * deriv f z * Star.star ( f z - w₂ ) |> Complex.re ) from by nlinarith [ show 0 < t₂ from lt_of_le_of_ne ht₂ ( Ne.symm ht₂_zero ) ] ] );
  convert h_pos using 2 ; norm_num [ Complex.ext_iff ] ; ring;
  rw [ ← eq_sub_iff_add_eq' ] at hab ; subst_vars ; ring