/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 5a32732c-b976-4c97-a69b-87ae33845bcf

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Set
open Filter
open Finset
open BigOperators

open scoped Topology

/-
Definition of an equidistributed sequence on [0,1].
-/
def equidistributed (x : ℕ → ℝ) : Prop :=
  ∀ (α β : ℝ) (hα : 0 ≤ α) (hβ : β ≤ 1) (h : α ≤ β),
    Tendsto (λ n : ℕ ↦ ((Finset.range n).filter (λ v ↦ α ≤ x v ∧ x v ≤ β)).card / (n : ℝ))
      atTop (𝓝 (β - α))

/-
If a sequence is equidistributed, then the average of any continuous function converges to its integral.
-/
theorem equidistributed_implies_continuous (x : ℕ → ℝ) (hx : ∀ n, 0 ≤ x n ∧ x n ≤ 1) (h : equidistributed x) :
    ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc 0 1) →
      Tendsto (λ n : ℕ ↦ ((Finset.range n).sum (λ i ↦ f (x i))) / (n : ℝ))
        atTop (𝓝 (∫ t in (0)..1, f t)) := by
  -- Fix a continuous function $f$ on $[0, 1]$.
  intro f hf;
  -- Since $f$ is continuous on $[0,1]$, it can be uniformly approximated by polynomials.
  have h_poly : ∀ ε > 0, ∃ p : Polynomial ℝ, ∀ t ∈ Set.Icc 0 1, abs (f t - p.eval t) < ε := by
    have h_weierstrass : ∀ ε > 0, ∃ p : Polynomial ℝ, ∀ t ∈ Set.Icc 0 1, abs (p.eval t - f t) < ε := by
      apply_rules [ exists_polynomial_near_of_continuousOn ];
    simpa only [ abs_sub_comm ] using h_weierstrass;
  -- By the equidistribution theorem, the average of $p(x_i)$ converges to the integral of $p$ over $[0,1]$.
  have h_poly_avg : ∀ p : Polynomial ℝ, Filter.Tendsto (fun n => (∑ i ∈ Finset.range n, p.eval (x i)) / (n : ℝ)) Filter.atTop (𝓝 (∫ t in (0 : ℝ)..1, p.eval t)) := by
    -- By the properties of the equidistribution theorem, the average of $x_i^k$ converges to the integral of $x^k$ over $[0,1]$.
    have h_moments : ∀ k : ℕ, Filter.Tendsto (fun n => (∑ i ∈ Finset.range n, (x i) ^ k) / (n : ℝ)) Filter.atTop (𝓝 (∫ t in (0 : ℝ)..1, t ^ k)) := by
      intro k;
      induction' k with k ih;
      · exact tendsto_const_nhds.congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with n hn; simp +decide [ hn ] );
      · -- By the properties of the equidistribution theorem, the average of $x_i^k$ converges to the integral of $x^k$ over $[0,1]$. We can use the fact that the integral of $x^k$ over $[0,1]$ is $\frac{1}{k+1}$.
        have h_integral : ∀ α β : ℝ, 0 ≤ α → α ≤ β → β ≤ 1 → Filter.Tendsto (fun n => (∑ i ∈ Finset.range n, (if x i ∈ Set.Icc α β then 1 else 0)) / (n : ℝ)) Filter.atTop (𝓝 (β - α)) := by
          aesop;
        -- By the properties of the equidistribution theorem, the average of $x_i^k$ converges to the integral of $x^k$ over $[0,1]$. We can use the fact that the integral of $x^k$ over $[0,1]$ is $\frac{1}{k+1}$ and the linearity of the integral.
        have h_integral : Filter.Tendsto (fun n => (∑ i ∈ Finset.range n, (∫ t in (0 : ℝ)..x i, t ^ k)) / (n : ℝ)) Filter.atTop (𝓝 (∫ t in (0 : ℝ)..1, ∫ u in (0 : ℝ)..t, u ^ k)) := by
          have h_integral : ∀ n, (∑ i ∈ Finset.range n, (∫ t in (0 : ℝ)..x i, t ^ k)) = ∫ t in (0 : ℝ)..1, (∑ i ∈ Finset.range n, (if x i ≥ t then 1 else 0)) * t ^ k := by
            intro n
            have h_integral : ∑ i ∈ Finset.range n, (∫ t in (0 : ℝ)..x i, t ^ k) = ∫ t in (0 : ℝ)..1, (∑ i ∈ Finset.range n, (if x i ≥ t then t ^ k else 0)) := by
              rw [ intervalIntegral.integral_finset_sum ];
              · refine' Finset.sum_congr rfl fun i _ => _;
                rw [ intervalIntegral.integral_of_le ( hx i |>.1 ), intervalIntegral.integral_of_le zero_le_one ];
                rw [ ← MeasureTheory.integral_indicator, ← MeasureTheory.integral_indicator ] <;> norm_num [ Set.indicator ];
                grind;
              · intro i hi; apply_rules [ MeasureTheory.IntegrableOn.intervalIntegrable ];
                exact MeasureTheory.Integrable.indicator ( continuous_pow k |> Continuous.integrableOn_Icc ) ( measurableSet_Iic );
            simpa only [ Finset.sum_mul _ _ _ ] using h_integral.trans ( by congr; ext; congr; ext; split_ifs <;> ring );
          have h_integral : Filter.Tendsto (fun n => (∫ t in (0 : ℝ)..1, (∑ i ∈ Finset.range n, (if x i ≥ t then 1 else 0)) * t ^ k) / (n : ℝ)) Filter.atTop (𝓝 (∫ t in (0 : ℝ)..1, (∫ u in (0 : ℝ)..t, u ^ k))) := by
            have h_integral : ∀ t ∈ Set.Icc (0 : ℝ) 1, Filter.Tendsto (fun n => (∑ i ∈ Finset.range n, (if x i ≥ t then 1 else 0)) / (n : ℝ)) Filter.atTop (𝓝 (1 - t)) := by
              grind
            have h_integral : Filter.Tendsto (fun n => ∫ t in (0 : ℝ)..1, (∑ i ∈ Finset.range n, (if x i ≥ t then 1 else 0)) * t ^ k / (n : ℝ)) Filter.atTop (𝓝 (∫ t in (0 : ℝ)..1, (1 - t) * t ^ k)) := by
              refine' intervalIntegral.tendsto_integral_filter_of_dominated_convergence _ _ _ _ _;
              use fun t => t ^ k;
              · simp +zetaDelta at *;
                use 1;
                intro n hn;
                refine' Measurable.aestronglyMeasurable _;
                refine' Measurable.mul _ _;
                · refine' Measurable.mul _ _;
                  · refine' measurable_of_tendsto_metrizable _ _;
                    use fun i t => ( ∑ j ∈ Finset.range n, if t ≤ x j then 1 else 0 ) / ( i : ℝ ) * i;
                    · exact fun i => Measurable.mul ( Measurable.div_const ( Finset.measurable_sum _ fun j _ => measurable_const.indicator ( measurableSet_Iic ) ) _ ) measurable_const;
                    · exact tendsto_const_nhds.congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with i hi; aesop );
                  · exact measurable_id.pow_const _;
                · exact measurable_const;
              · norm_num +zetaDelta at *;
                use 1;
                intro n hn; filter_upwards [ ] with t ht₁ ht₂; rw [ abs_of_nonneg ht₁.le ] ; rw [ div_le_iff₀ ( by positivity ) ] ;
                rw [ mul_comm ] ; gcongr ; exact le_trans ( Finset.card_filter_le _ _ ) ( by norm_num );
              · norm_num;
              · filter_upwards [ ] with t ht using by simpa [ mul_div_right_comm ] using h_integral t ( by constructor <;> cases Set.mem_uIoc.mp ht <;> linarith ) |> Filter.Tendsto.mul_const _;
            convert h_integral using 2 <;> norm_num [ sub_mul ];
            norm_num [ ← pow_succ' ];
            rw [ inv_eq_one_div, inv_eq_one_div, div_div, div_sub_div, div_eq_div_iff ] <;> ring <;> positivity;
          aesop;
        convert h_integral.mul_const ( k + 1 : ℝ ) using 2 <;> norm_num [ integral_pow ] ; ring;
        · norm_num [ ← Finset.sum_mul _ _ _ ] ; ring;
          -- Combine like terms and simplify the expression.
          field_simp
          ring;
        · rw [ div_mul_cancel₀ _ ( by positivity ) ];
    simp_all +decide [ Polynomial.eval_eq_sum_range ];
    intro p; simp +decide [ Finset.sum_div _ _ _, Finset.mul_sum _ _ _, mul_div_assoc ] ;
    simp_all +decide [ ← Finset.mul_sum _ _ _, ← Finset.sum_div, ← Finset.sum_mul, div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Finset.sum_mul ];
    simp_all +decide [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul, ← Finset.sum_comm, intervalIntegral.integral_finset_sum ];
    exact tendsto_finset_sum _ fun i hi => by simpa [ mul_assoc, mul_comm, mul_left_comm ] using h_moments i |> Filter.Tendsto.mul_const ( p.coeff i ) ;
  -- By the properties of the integral, we can bound the difference between the averages of $f$ and $p$.
  have h_diff : ∀ ε > 0, ∃ p : Polynomial ℝ, ∀ n : ℕ, abs ((∑ i ∈ Finset.range n, f (x i)) / (n : ℝ) - (∑ i ∈ Finset.range n, p.eval (x i)) / (n : ℝ)) ≤ ε ∧ abs ((∫ t in (0 : ℝ)..1, f t) - (∫ t in (0 : ℝ)..1, p.eval t)) ≤ ε := by
    intro ε hε; obtain ⟨ p, hp ⟩ := h_poly ( ε / 2 ) ( half_pos hε ) ; use p; intro n; refine' ⟨ _, _ ⟩;
    · rw [ ← sub_div, abs_div ];
      exact div_le_of_le_mul₀ ( by positivity ) ( by positivity ) ( by rw [ ← Finset.sum_sub_distrib ] ; exact le_trans ( Finset.abs_sum_le_sum_abs _ _ ) ( le_trans ( Finset.sum_le_sum fun i hi => le_of_lt ( hp _ ( hx i ) ) ) ( by norm_num; nlinarith ) ) );
    · rw [ ← intervalIntegral.integral_sub ];
      · rw [ intervalIntegral.integral_of_le zero_le_one ];
        refine' le_trans ( MeasureTheory.norm_integral_le_integral_norm ( _ : ℝ → ℝ ) ) ( le_trans ( MeasureTheory.integral_mono_of_nonneg _ _ _ ) _ );
        refine' fun t => ε / 2;
        · exact Filter.Eventually.of_forall fun x => norm_nonneg _;
        · norm_num;
        · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with t ht using le_of_lt ( hp t <| Set.Ioc_subset_Icc_self ht );
        · norm_num ; linarith;
      · exact hf.intervalIntegrable_of_Icc ( by norm_num );
      · exact p.continuous.intervalIntegrable _ _;
  rw [ Metric.tendsto_nhds ];
  intro ε hε; rcases h_diff ( ε / 3 ) ( by positivity ) with ⟨ p, hp ⟩ ; filter_upwards [ h_poly_avg p |> fun h => h.eventually ( Metric.ball_mem_nhds _ <| show 0 < ε / 3 by positivity ) ] with n hn; exact abs_lt.mpr ⟨ by linarith [ abs_lt.mp hn, abs_le.mp ( hp n |>.1 ), abs_le.mp ( hp n |>.2 ) ], by linarith [ abs_lt.mp hn, abs_le.mp ( hp n |>.1 ), abs_le.mp ( hp n |>.2 ) ] ⟩ ;

/-
If the average of any continuous function converges to its integral, then the sequence is equidistributed.
-/
theorem continuous_implies_equidistributed (x : ℕ → ℝ) (hx : ∀ n, 0 ≤ x n ∧ x n ≤ 1)
    (h : ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc 0 1) →
      Tendsto (λ n : ℕ ↦ ((Finset.range n).sum (λ i ↦ f (x i))) / (n : ℝ))
        atTop (𝓝 (∫ t in (0)..1, f t))) :
    equidistributed x := by
  intro α β hα hβ hαβ;
  -- Define a sequence of continuous functions $f_\epsilon$ that approximate the indicator function of $[\alpha, \beta]$.
  have h_seq : ∀ ε > 0, ∃ f : ℝ → ℝ, ContinuousOn f (Set.Icc 0 1) ∧ (∀ t ∈ Set.Icc 0 1, f t ≥ if α ≤ t ∧ t ≤ β then 1 else 0) ∧ (∀ t ∈ Set.Icc 0 1, f t ≤ if α - ε ≤ t ∧ t ≤ β + ε then 1 else 0) := by
    intro ε hε_pos
    use fun t => max 0 (min 1 ((t - (α - ε)) / ε)) * max 0 (min 1 ((β + ε - t) / ε));
    refine' ⟨ _, _, _ ⟩;
    · fun_prop;
    · field_simp;
      intro t ht; split_ifs;
      · rw [ max_eq_right, max_eq_right ] <;> norm_num;
        · rw [ min_def, min_def ] ; split_ifs <;> nlinarith [ mul_div_cancel₀ ( t - ( α - ε ) ) hε_pos.ne', mul_div_cancel₀ ( β + ε - t ) hε_pos.ne' ];
        · exact div_nonneg ( by linarith ) hε_pos.le;
        · exact div_nonneg ( by linarith ) hε_pos.le;
      · positivity;
    · intro t ht; split_ifs <;> norm_num;
      · exact mul_le_one₀ ( max_le_iff.mpr ⟨ by norm_num, min_le_of_left_le <| by norm_num ⟩ ) ( by positivity ) ( max_le_iff.mpr ⟨ by norm_num, min_le_of_left_le <| by norm_num ⟩ );
      · cases max_cases ( 0 : ℝ ) ( Min.min 1 ( ( t - ( α - ε ) ) / ε ) ) <;> cases max_cases ( 0 : ℝ ) ( Min.min 1 ( ( β + ε - t ) / ε ) ) <;> simp_all +decide;
        linarith [ ‹α ≤ t + ε → β + ε < t› ( by linarith ) ];
  have h_seq_approx : ∀ ε > 0, ∃ f : ℝ → ℝ, ContinuousOn f (Set.Icc 0 1) ∧ (∀ t ∈ Set.Icc 0 1, f t ≥ if α ≤ t ∧ t ≤ β then 1 else 0) ∧ (∀ t ∈ Set.Icc 0 1, f t ≤ if α - ε ≤ t ∧ t ≤ β + ε then 1 else 0) ∧ (∫ t in (0)..1, f t) ≤ (β - α) + 2 * ε := by
    intro ε hε_pos
    obtain ⟨f, hf_cont, hf_approx⟩ := h_seq ε hε_pos
    have h_integral_approx : ∫ t in (0)..1, f t ≤ ∫ t in (max 0 (α - ε))..(min 1 (β + ε)), 1 := by
      have h_integral_approx : ∫ t in (0)..1, f t ≤ ∫ t in (0)..1, (if α - ε ≤ t ∧ t ≤ β + ε then 1 else 0) := by
        apply_rules [ intervalIntegral.integral_mono_on ];
        · norm_num;
        · exact hf_cont.intervalIntegrable_of_Icc ( by norm_num );
        · rw [ intervalIntegrable_iff ];
          refine' MeasureTheory.Integrable.mono' _ _ _;
          refine' fun t => 1;
          · norm_num;
          · exact Measurable.aestronglyMeasurable ( by exact Measurable.ite ( measurableSet_Icc ) measurable_const measurable_const );
          · exact Filter.Eventually.of_forall fun x => by split_ifs <;> norm_num;
        · exact hf_approx.2;
      refine le_trans h_integral_approx ?_;
      rw [ intervalIntegral.integral_of_le, intervalIntegral.integral_of_le ];
      · rw [ ← MeasureTheory.integral_Icc_eq_integral_Ioc, ← MeasureTheory.integral_Icc_eq_integral_Ioc ];
        rw [ ← MeasureTheory.integral_indicator, ← MeasureTheory.integral_indicator ] <;> norm_num [ Set.indicator ];
        grind;
      · cases max_cases ( 0 : ℝ ) ( α - ε ) <;> cases min_cases ( 1 : ℝ ) ( β + ε ) <;> linarith;
      · norm_num;
    norm_num at *;
    exact ⟨ f, hf_cont, hf_approx.1, hf_approx.2, by cases max_cases 0 ( α - ε ) <;> cases min_cases 1 ( β + ε ) <;> linarith ⟩;
  have h_seq_approx_lower : ∀ ε > 0, ∃ f : ℝ → ℝ, ContinuousOn f (Set.Icc 0 1) ∧ (∀ t ∈ Set.Icc 0 1, f t ≤ if α ≤ t ∧ t ≤ β then 1 else 0) ∧ (∀ t ∈ Set.Icc 0 1, f t ≥ if α + ε ≤ t ∧ t ≤ β - ε then 1 else 0) ∧ (∫ t in (0)..1, f t) ≥ (β - α) - 2 * ε := by
    intros ε hε_pos
    by_cases h_case : α + ε ≤ β - ε;
    · -- Define a continuous function $f$ that is 1 on $[\alpha + \epsilon, \beta - \epsilon]$ and 0 outside $[\alpha, \beta]$.
      obtain ⟨f, hf_cont, hf_bounds⟩ : ∃ f : ℝ → ℝ, ContinuousOn f (Set.Icc 0 1) ∧ (∀ t ∈ Set.Icc 0 1, f t ≤ if α ≤ t ∧ t ≤ β then 1 else 0) ∧ (∀ t ∈ Set.Icc 0 1, f t ≥ if α + ε ≤ t ∧ t ≤ β - ε then 1 else 0) := by
        use fun t => min 1 (max 0 ((min (t - (α + ε)) (β - ε - t)) / ε + 1));
        refine' ⟨ _, _, _ ⟩;
        · fun_prop;
        · field_simp;
          intro t ht; split_ifs <;> norm_num;
          rw [ div_le_iff₀ hε_pos ];
          cases min_cases ( t - ( α + ε ) ) ( β - ε - t ) <;> cases lt_or_ge t α <;> cases lt_or_ge t β <;> first | linarith | exact False.elim <| ‹¬ ( α ≤ t ∧ t ≤ β ) › ⟨ by linarith, by linarith ⟩;
        · norm_num +zetaDelta at *;
          intro t ht₁ ht₂; split_ifs <;> norm_num ;
          exact div_nonneg ( le_min ( by linarith ) ( by linarith ) ) hε_pos.le;
      refine' ⟨ f, hf_cont, hf_bounds.1, hf_bounds.2, _ ⟩;
      have h_integral_lower_bound : ∫ t in (0)..1, f t ≥ ∫ t in (α + ε)..(β - ε), f t := by
        apply_rules [ intervalIntegral.integral_mono_interval ];
        · linarith;
        · linarith;
        · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with t ht using le_trans ( by positivity ) ( hf_bounds.2 t <| Set.Ioc_subset_Icc_self ht );
        · exact hf_cont.intervalIntegrable_of_Icc ( by norm_num );
      have h_integral_lower_bound : ∫ t in (α + ε)..(β - ε), f t ≥ ∫ t in (α + ε)..(β - ε), 1 := by
        refine' intervalIntegral.integral_mono_on _ _ _ _ <;> norm_num;
        · linarith;
        · apply_rules [ ContinuousOn.intervalIntegrable, hf_cont ];
          exact hf_cont.mono ( by rw [ Set.uIcc_of_le ( by linarith ) ] ; exact Set.Icc_subset_Icc ( by linarith ) ( by linarith ) );
        · exact fun t ht₁ ht₂ => hf_bounds.2 t ⟨ by linarith, by linarith ⟩ |> le_trans ( by rw [ if_pos ⟨ ht₁, ht₂ ⟩ ] );
      norm_num at *; linarith;
    · use fun _ => 0;
      norm_num;
      exact ⟨ continuousOn_const, fun t ht₁ ht₂ => by split_ifs <;> norm_num, fun t ht₁ ht₂ => by split_ifs <;> linarith, by linarith ⟩;
  -- By the properties of the average and the integral, we can bound the average of the indicator function.
  have h_bound : ∀ ε > 0, ∃ N : ℕ, ∀ n ≥ N, (∑ i ∈ Finset.range n, (if α ≤ x i ∧ x i ≤ β then 1 else 0)) / (n : ℝ) ≤ (β - α) + 2 * ε + ε ∧ (∑ i ∈ Finset.range n, (if α ≤ x i ∧ x i ≤ β then 1 else 0)) / (n : ℝ) ≥ (β - α) - 2 * ε - ε := by
    intro ε hε_pos
    obtain ⟨f_upper, hf_upper_cont, hf_upper_ge, hf_upper_le, hf_upper_integral⟩ := h_seq_approx ε hε_pos
    obtain ⟨f_lower, hf_lower_cont, hf_lower_le, hf_lower_ge, hf_lower_integral⟩ := h_seq_approx_lower ε hε_pos;
    have h_bound_upper : ∃ N : ℕ, ∀ n ≥ N, (∑ i ∈ Finset.range n, f_upper (x i)) / (n : ℝ) ≤ (β - α) + 2 * ε + ε := by
      have := h f_upper hf_upper_cont;
      exact Filter.eventually_atTop.mp ( this.eventually ( ge_mem_nhds <| by linarith ) )
    have h_bound_lower : ∃ N : ℕ, ∀ n ≥ N, (∑ i ∈ Finset.range n, f_lower (x i)) / (n : ℝ) ≥ (β - α) - 2 * ε - ε := by
      have := h f_lower hf_lower_cont;
      exact Filter.eventually_atTop.mp ( this.eventually ( le_mem_nhds <| by linarith ) );
    obtain ⟨ N₁, hN₁ ⟩ := h_bound_upper; obtain ⟨ N₂, hN₂ ⟩ := h_bound_lower; use Max.max N₁ N₂; intro n hn; refine' ⟨ _, _ ⟩ <;> norm_num at *;
    · refine' le_trans _ ( hN₁ n hn.1 );
      gcongr;
      exact le_trans ( by norm_num ) ( Finset.sum_le_sum fun i hi => hf_upper_ge ( x i ) ( hx i |>.1 ) ( hx i |>.2 ) );
    · refine' le_trans ( hN₂ n hn.2 ) _;
      gcongr;
      exact le_trans ( Finset.sum_le_sum fun i hi => hf_lower_le ( x i ) ( hx i |>.1 ) ( hx i |>.2 ) ) ( by norm_num [ Finset.sum_ite ] );
  rw [ Metric.tendsto_nhds ];
  simp +zetaDelta at *;
  exact fun ε hε => by obtain ⟨ N, hN ⟩ := h_bound ( ε / 6 ) ( by positivity ) ; exact ⟨ N, fun n hn => abs_lt.mpr ⟨ by linarith [ hN n hn ], by linarith [ hN n hn ] ⟩ ⟩ ;

/-
Equidistribution is equivalent to the convergence of averages for all continuous functions.
-/
theorem equidistributed_iff_continuous_iff (x : ℕ → ℝ) (hx : ∀ n, 0 ≤ x n ∧ x n ≤ 1) :
    equidistributed x ↔
    ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc 0 1) →
      Tendsto (λ n : ℕ ↦ ((Finset.range n).sum (λ i ↦ f (x i))) / (n : ℝ))
        atTop (𝓝 (∫ t in (0)..1, f t)) := by
  constructor
  · exact equidistributed_implies_continuous x hx
  · exact continuous_implies_equidistributed x hx

/-
A continuous trapezoidal function that is 0 outside (a, d), 1 on [b, c], and linear in between.
-/
def continuous_trap (a b c d : ℝ) (x : ℝ) : ℝ :=
  max 0 (min 1 (min ((x - a) / (b - a)) ((d - x) / (d - c))))

/-
The trapezoidal function is continuous.
-/
lemma continuous_trap_continuous (a b c d : ℝ) (h1 : a < b) (h2 : c < d) :
    Continuous (continuous_trap a b c d) := by
  unfold continuous_trap;
  fun_prop (disch := norm_num)

/-
The trapezoidal function is bounded between 0 and 1.
-/
lemma continuous_trap_bounds (a b c d : ℝ) (h1 : a < b) (h2 : b ≤ c) (h3 : c < d) (x : ℝ) :
    0 ≤ continuous_trap a b c d x ∧ continuous_trap a b c d x ≤ 1 := by
  unfold continuous_trap; aesop

/-
Support properties of the trapezoidal function.
-/
lemma continuous_trap_support (a b c d : ℝ) (h1 : a < b) (h2 : b ≤ c) (h3 : c < d) (x : ℝ) :
    (continuous_trap a b c d x ≠ 0 → a < x ∧ x < d) ∧
    (b ≤ x ∧ x ≤ c → continuous_trap a b c d x = 1) := by
  constructor <;> intro h;
  · unfold continuous_trap at h;
    aesop;
  · -- By definition of continuous_trap, we know that for $b \leq x \leq c$, both $(x - a) / (b - a) \geq 1$ and $(d - x) / (d - c) \geq 1$.
    have h_ge_one : (x - a) / (b - a) ≥ 1 ∧ (d - x) / (d - c) ≥ 1 := by
      exact ⟨ by rw [ ge_iff_le ] ; rw [ le_div_iff₀ ] <;> linarith, by rw [ ge_iff_le ] ; rw [ le_div_iff₀ ] <;> linarith ⟩;
    exact Eq.symm ( by unfold continuous_trap; aesop )

/-
Upper trapezoidal approximation of the indicator function of [α, β].
-/
def trap_upper (α β ε : ℝ) (x : ℝ) : ℝ := continuous_trap (α - ε) α β (β + ε) x

/-
Lower trapezoidal approximation of the indicator function of [α, β].
-/
def trap_lower (α β ε : ℝ) (x : ℝ) : ℝ := continuous_trap α (α + ε) (β - ε) β x

/-
The upper trapezoidal approximation is integrable.
-/
lemma trap_upper_integrable (α β ε : ℝ) (hε : 0 < ε) :
    IntervalIntegrable (trap_upper α β ε) MeasureTheory.volume 0 1 := by
  apply Continuous.intervalIntegrable
  apply continuous_trap_continuous
  linarith
  linarith

/-
The lower trapezoidal approximation is integrable.
-/
lemma trap_lower_integrable (α β ε : ℝ) (hε : 0 < ε) :
    IntervalIntegrable (trap_lower α β ε) MeasureTheory.volume 0 1 := by
  apply Continuous.intervalIntegrable
  apply continuous_trap_continuous
  linarith
  linarith

/-
The integral of the difference between the upper and lower trapezoidal approximations is bounded by 4ε.
-/
lemma trap_integral_diff (α β ε : ℝ) (hα : 0 ≤ α) (hβ : β ≤ 1) (hαβ : α ≤ β) (hε : 0 < ε) :
    ∫ x in Set.Ioc 0 1, (trap_upper α β ε x - trap_lower α β ε x) ≤ 4 * ε := by
  rw [ MeasureTheory.integral_Ioc_eq_integral_Ioo ];
  -- The integral of the difference between the upper and lower trapezoidal approximations over (0,1) is at most the integral over the interval where the difference is non-zero, which is (α - ε, α + ε) ∪ (β - ε, β + ε).
  have h_diff_nonzero : ∀ t ∈ Set.Ioo 0 1, trap_upper α β ε t - trap_lower α β ε t ≤ if t ∈ Set.Ioo (α - ε) (α + ε) ∪ Set.Ioo (β - ε) (β + ε) then 1 else 0 := by
    intro t ht
    by_cases h_case : t ∈ Set.Ioo (α - ε) (α + ε) ∪ Set.Ioo (β - ε) (β + ε);
    · -- Since $t \in (\beta - \epsilon, \beta + \epsilon)$, we have $trap_upper α β ε t \leq 1$ and $trap_lower α β ε t \geq 0$.
      have h_bounds : trap_upper α β ε t ≤ 1 ∧ trap_lower α β ε t ≥ 0 := by
        exact ⟨ by unfold trap_upper; exact max_le_iff.mpr ⟨ by norm_num, min_le_of_left_le <| by norm_num ⟩, by unfold trap_lower; exact le_max_of_le_left <| by norm_num ⟩;
      grind;
    · simp [h_case];
      unfold trap_upper trap_lower;
      unfold continuous_trap;
      norm_num [ sub_sub_eq_add_sub ] at *;
      by_cases h_case1 : α - ε < t <;> by_cases h_case2 : β - ε < t <;> simp_all +decide [ div_le_iff₀, le_div_iff₀ ];
      · exact Or.inr ⟨ ⟨ by linarith, Or.inl <| by linarith ⟩, by linarith, Or.inl <| by linarith ⟩;
      · exact Or.inl <| Or.inl <| by linarith;
  refine' le_trans ( MeasureTheory.setIntegral_mono_on _ _ measurableSet_Ioo h_diff_nonzero ) _;
  · refine' Continuous.integrableOn_Icc _ |> fun h => h.mono_set <| Set.Ioo_subset_Icc_self;
    exact Continuous.sub ( continuous_trap_continuous _ _ _ _ ( by linarith ) ( by linarith ) ) ( continuous_trap_continuous _ _ _ _ ( by linarith ) ( by linarith ) );
  · refine' MeasureTheory.Integrable.mono' _ _ _;
    exacts [ fun _ => 1, by norm_num, by exact Measurable.aestronglyMeasurable ( by exact Measurable.ite ( by exact MeasurableSet.union ( measurableSet_Ioo ) ( measurableSet_Ioo ) ) measurable_const measurable_const ), Filter.Eventually.of_forall fun x => by split_ifs <;> norm_num ];
  · -- The integral of the indicator function over the union of intervals is just the sum of the lengths of those intervals.
    have h_indicator_integral : ∫ x in Set.Ioo 0 1, (if x ∈ Set.Ioo (α - ε) (α + ε) ∪ Set.Ioo (β - ε) (β + ε) then 1 else 0) ≤ ∫ x in Set.Ioo (α - ε) (α + ε) ∪ Set.Ioo (β - ε) (β + ε), (1 : ℝ) := by
      rw [ ← MeasureTheory.integral_indicator, ← MeasureTheory.integral_indicator ] <;> norm_num [ Set.indicator ];
      refine' MeasureTheory.integral_mono_of_nonneg _ _ _;
      · exact Filter.Eventually.of_forall fun x => by positivity;
      · refine' MeasureTheory.Integrable.congr _ _;
        refine' fun x => Set.indicator ( Set.Ioo ( α - ε ) ( α + ε ) ∪ Set.Ioo ( β - ε ) ( β + ε ) ) ( fun _ => 1 ) x;
        · rw [ MeasureTheory.integrable_indicator_iff ] <;> norm_num;
        · norm_num [ Filter.EventuallyEq, Set.indicator ];
      · filter_upwards [ ] with x using by aesop;
    norm_num +zetaDelta at *;
    refine' le_trans h_indicator_integral _;
    refine' le_trans ( ENNReal.toReal_mono _ <| MeasureTheory.measure_union_le _ _ ) _ <;> norm_num;
    rw [ ENNReal.toReal_add ] <;> norm_num ; linarith [ ENNReal.toReal_ofReal ( show 0 ≤ ε + ε by linarith ) ]

/-
Lower approximation of x * indicator.
-/
def trap_x_lower (α β ε : ℝ) (x : ℝ) : ℝ := x * trap_lower α β ε x

/-
Upper approximation of x * indicator.
-/
def trap_x_upper (α β ε : ℝ) (x : ℝ) : ℝ := x * trap_upper α β ε x

/-
The sandwich inequality for x * indicator.
-/
lemma trap_x_sandwich (α β ε : ℝ) (hα : 0 ≤ α) (hβ : β ≤ 1) (hαβ : α ≤ β) (hε : 0 < ε) (x : ℝ) (hx : 0 ≤ x ∧ x ≤ 1) :
    trap_x_lower α β ε x ≤ (if α ≤ x ∧ x ≤ β then x else 0) ∧
    (if α ≤ x ∧ x ≤ β then x else 0) ≤ trap_x_upper α β ε x := by
  -- Let's split into cases based on whether x is in [α, β].
  by_cases h : α ≤ x ∧ x ≤ β;
  · -- Since $x \in [\alpha, \beta]$, we have $\text{trap\_upper} \alpha \beta \epsilon x = 1$ and $\text{trap\_lower} \alpha \beta \epsilon x \leq 1$.
    have h_upper : trap_upper α β ε x = 1 := by
      apply (continuous_trap_support (α - ε) α β (β + ε) (by linarith) (by linarith) (by linarith) x).right h;
    simp_all +decide [ trap_x_lower, trap_x_upper ];
    exact mul_le_of_le_one_right hx.1 ( by exact ( show trap_lower α β ε x ≤ 1 from by exact ( show continuous_trap α ( α + ε ) ( β - ε ) β x ≤ 1 from by exact ( show max 0 ( min 1 ( min ( ( x - α ) / ( α + ε - α ) ) ( ( β - x ) / ( β - ( β - ε ) ) ) ) ) ≤ 1 from by exact max_le ( by norm_num ) ( min_le_left _ _ ) ) ) ) );
  · split_ifs ; simp_all +decide [ trap_x_lower, trap_x_upper ];
    constructor;
    · unfold trap_lower;
      unfold continuous_trap;
      rw [ max_eq_left ] <;> norm_num;
      exact Classical.or_iff_not_imp_left.2 fun h' => by rw [ div_le_iff₀ hε ] at *; contrapose! h; constructor <;> linarith;
    · exact mul_nonneg hx.1 ( by unfold trap_upper; exact le_max_of_le_left ( by norm_num ) )

/-
The integral of the difference of the sandwich functions is small.
-/
lemma trap_x_integral_diff (α β ε : ℝ) (hα : 0 ≤ α) (hβ : β ≤ 1) (hαβ : α ≤ β) (hε : 0 < ε) :
    ∫ x in Set.Ioc 0 1, (trap_x_upper α β ε x - trap_x_lower α β ε x) ≤ 4 * ε := by
  -- Since $x \leq 1$ for all $x \in [0, 1]$, we have $\int_{0}^{1} x \cdot (\text{trap}_{\text{upper}} - \text{trap}_{\text{lower}}) \leq \int_{0}^{1} (\text{trap}_{\text{upper}} - \text{trap}_{\text{lower}})$.
  have h_integral_le : ∫ x in Set.Ioc 0 1, x * (trap_upper α β ε x - trap_lower α β ε x) ≤ ∫ x in Set.Ioc 0 1, (trap_upper α β ε x - trap_lower α β ε x) := by
    refine' MeasureTheory.setIntegral_mono_on _ _ measurableSet_Ioc fun x hx => mul_le_of_le_one_left ( _ ) hx.2;
    · exact Continuous.integrableOn_Ioc ( by exact Continuous.mul continuous_id ( by exact Continuous.sub ( continuous_trap_continuous _ _ _ _ ( by linarith ) ( by linarith ) ) ( continuous_trap_continuous _ _ _ _ ( by linarith ) ( by linarith ) ) ) );
    · exact Continuous.integrableOn_Ioc ( by exact Continuous.sub ( continuous_trap_continuous _ _ _ _ ( by linarith ) ( by linarith ) ) ( continuous_trap_continuous _ _ _ _ ( by linarith ) ( by linarith ) ) );
    · unfold trap_upper trap_lower;
      unfold continuous_trap;
      grind;
  simpa only [ mul_sub, mul_one ] using h_integral_le.trans ( by simpa only [ mul_sub, mul_one ] using trap_integral_diff α β ε hα hβ hαβ hε )

/-
The integrals of the upper and lower approximations are close to the target value (beta^2 - alpha^2)/2.
-/
lemma trap_x_integral_close (α β ε : ℝ) (hα : 0 ≤ α) (hβ : β ≤ 1) (hαβ : α ≤ β) (hε : 0 < ε) :
    abs (∫ x in Set.Ioc 0 1, trap_x_upper α β ε x - (β^2 - α^2) / 2) ≤ 4 * ε ∧
    abs (∫ x in Set.Ioc 0 1, trap_x_lower α β ε x - (β^2 - α^2) / 2) ≤ 4 * ε := by
  -- By the properties of the trapezoidal functions, we have that $\int_0^1 \text{trap}_x \text{lower}(\alpha, \beta, \epsilon, x) \, dx \leq \int_0^1 \text{trap}_x \text{upper}(\alpha, \beta, \epsilon, x) \, dx$.
  have h_integral_bounds : ∫ x in (Set.Ioc 0 1), trap_x_lower α β ε x ≤ (β^2 - α^2) / 2 ∧ (β^2 - α^2) / 2 ≤ ∫ x in (Set.Ioc 0 1), trap_x_upper α β ε x := by
    have h_integral_bounds : ∫ x in (Set.Ioc 0 1), (if α ≤ x ∧ x ≤ β then x else 0) = (β^2 - α^2) / 2 := by
      -- Split the integral into two parts: over $[α, β]$ and over $[0, 1] \setminus [α, β]$.
      have h_split : ∫ x in Set.Ioc 0 1, (if α ≤ x ∧ x ≤ β then x else 0) = ∫ x in Set.Icc α β, x := by
        rw [ ← MeasureTheory.integral_Icc_eq_integral_Ioc, ← MeasureTheory.integral_indicator, ← MeasureTheory.integral_indicator ] <;> norm_num [ Set.indicator ];
        grind;
      rw [ h_split, MeasureTheory.integral_Icc_eq_integral_Ioc, ← intervalIntegral.integral_of_le ] <;> norm_num ; linarith;
    refine' ⟨ h_integral_bounds ▸ MeasureTheory.setIntegral_mono_on _ _ _ _, h_integral_bounds ▸ MeasureTheory.setIntegral_mono_on _ _ _ _ ⟩;
    any_goals norm_num;
    any_goals intro x hx₁ hx₂; exact trap_x_sandwich α β ε hα hβ hαβ hε x ⟨ hx₁.le, hx₂ ⟩ |>.2;
    · exact Continuous.integrableOn_Ioc ( by exact Continuous.mul continuous_id ( by exact continuous_iff_continuousAt.mpr fun x => by exact ContinuousAt.tendsto ( by exact continuous_iff_continuousAt.mp ( continuous_trap_continuous _ _ _ _ ( by linarith ) ( by linarith ) ) _ ) ) );
    · refine' MeasureTheory.Integrable.mono' _ _ _;
      refine' fun x => |x|;
      · exact Continuous.integrableOn_Ioc ( by continuity );
      · exact Measurable.aestronglyMeasurable ( by exact Measurable.ite ( measurableSet_Icc ) measurable_id measurable_const );
      · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with x hx using by split_ifs <;> norm_num;
    · exact fun x hx₁ hx₂ => trap_x_sandwich α β ε hα hβ hαβ hε x ⟨ hx₁.le, hx₂ ⟩ |>.1;
    · refine' MeasureTheory.Integrable.mono' _ _ _;
      refine' fun x => |x|;
      · exact Continuous.integrableOn_Ioc ( by continuity );
      · exact Measurable.aestronglyMeasurable ( by exact Measurable.ite ( measurableSet_Icc ) measurable_id measurable_const );
      · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with x hx using by split_ifs <;> norm_num;
    · exact Continuous.integrableOn_Ioc ( by exact Continuous.mul continuous_id <| by exact continuous_trap_continuous _ _ _ _ ( by linarith ) ( by linarith ) );
  rw [ MeasureTheory.integral_sub, MeasureTheory.integral_sub ] <;> norm_num [ ← intervalIntegral.integral_of_le ] at *;
  · have h_integral_diff : ∫ x in (Set.Ioc 0 1), (trap_x_upper α β ε x - trap_x_lower α β ε x) ≤ 4 * ε := by
      exact?;
    rw [ ← intervalIntegral.integral_of_le zero_le_one, intervalIntegral.integral_sub ] at * <;> norm_num at *;
    · exact ⟨ abs_le.mpr ⟨ by linarith, by linarith ⟩, abs_le.mpr ⟨ by linarith, by linarith ⟩ ⟩;
    · apply_rules [ Continuous.intervalIntegrable ];
      apply_rules [ Continuous.mul, Continuous.max, Continuous.min, continuous_id, continuous_const ];
      · continuity;
      · fun_prop;
    · apply_rules [ ContinuousOn.intervalIntegrable ];
      exact ContinuousOn.mul continuousOn_id <| ContinuousOn.congr ( show ContinuousOn ( fun x => continuous_trap α ( α + ε ) ( β - ε ) β x ) ( Set.uIcc 0 1 ) from Continuous.continuousOn <| by exact continuous_trap_continuous _ _ _ _ ( by linarith ) ( by linarith ) ) fun x hx => rfl;
  · exact Continuous.integrableOn_Ioc ( by exact Continuous.mul continuous_id ( continuous_trap_continuous α ( α + ε ) ( β - ε ) β ( by linarith ) ( by linarith ) ) );
  · refine' Continuous.integrableOn_Ioc _;
    exact Continuous.mul continuous_id <| continuous_trap_continuous _ _ _ _ ( by linarith ) ( by linarith )