/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 9d2eed78-7f4f-4904-881d-b641c2bc8d03
-/

/-
We have constructed a function f(x) that satisfies the conditions of Polya-Szego Problem 114.1. The function is defined piecewise based on a sequence a_n = 1/(n(log n)^2). We proved that f is positive, bounded on finite intervals, and integrable on finite intervals. We further proved that the improper integral of f converges (corresponding to α=1), but the improper integral of f^α diverges for any α ≠ 1.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open MeasureTheory Filter Topology Set Real

/-
Define the sequence a_n and the function f(x) for the problem.
-/
noncomputable def seq_a (n : ℕ) : ℝ :=
  if n < 3 then 1/2 else 1 / (n * (Real.log n)^2)

noncomputable def solution_f (x : ℝ) : ℝ :=
  let n := Nat.floor x + 1
  if x < n - (seq_a n)^2 then seq_a n else 1 / seq_a n

/-
The sequence a_n is always positive.
-/
lemma seq_a_pos (n : ℕ) : 0 < seq_a n := by
  unfold seq_a;
  split_ifs <;> norm_num;
  exact mul_pos ( inv_pos.mpr ( sq_pos_of_pos ( Real.log_pos ( by norm_cast; linarith ) ) ) ) ( inv_pos.mpr ( by norm_cast; linarith ) )

/-
The sequence a_n is bounded by 1.
-/
lemma seq_a_le_one (n : ℕ) : seq_a n ≤ 1 := by
  unfold seq_a;
  split_ifs <;> norm_num;
  exact mul_le_one₀ ( inv_le_one_of_one_le₀ <| one_le_pow₀ <| Real.le_log_iff_exp_le ( by norm_cast; linarith ) |>.2 <| by exact Real.exp_one_lt_d9.le.trans <| by norm_num; linarith [ show ( n : ℝ ) ≥ 3 by norm_cast; linarith ] ) ( by positivity ) ( inv_le_one_of_one_le₀ <| by norm_cast; linarith )

/-
The sequence a_n tends to 0 as n goes to infinity.
-/
lemma seq_a_tendsto_zero : Tendsto seq_a atTop (𝓝 0) := by
  have h_lim_inf : Filter.Tendsto (fun n => 1 / (n * (Real.log n)^2 : ℝ)) Filter.atTop (𝓝 0) := by
    norm_num +zetaDelta at *;
    exact le_trans ( Filter.Tendsto.mul ( Filter.Tendsto.inv_tendsto_atTop <| Filter.Tendsto.comp ( Filter.tendsto_pow_atTop ( by norm_num ) ) <| Real.tendsto_log_atTop ) <| tendsto_inv_atTop_zero ) <| by norm_num;
  have h_lim_inf : Filter.Tendsto (fun n => if n < 3 then 1/2 else 1 / (n * (Real.log n)^2 : ℝ)) Filter.atTop (𝓝 0) := by
    exact Filter.Tendsto.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 3 ] with n hn; rw [ if_neg hn.not_lt ] ) h_lim_inf;
  convert h_lim_inf.comp tendsto_natCast_atTop_atTop using 1;
  ext; unfold seq_a; aesop;

/-
The function solution_f is positive for non-negative x.
-/
lemma solution_f_pos (x : ℝ) (hx : 0 ≤ x) : 0 < solution_f x := by
  -- By definition of `solution_f`, we know that it is either `seq_a n` or `1/seq_a n`, both of which are positive for `n ≥ 3`.
  simp [solution_f];
  split_ifs <;> [ exact seq_a_pos _; exact inv_pos.mpr ( seq_a_pos _ ) ]

/-
The function solution_f is bounded on any finite interval [a, b].
-/
lemma solution_f_bounded_on_Icc (a b : ℝ) (ha : 0 ≤ a) (hab : a ≤ b) :
  ∃ M : ℝ, ∀ x ∈ Set.Icc a b, |solution_f x| ≤ M := by
  -- Let $N$ be the maximum of $\lfloor b \rfloor$ and $3$.
  obtain ⟨N, hN⟩ : ∃ N : ℕ, ∀ x ∈ Set.Icc a b, Nat.floor x + 1 ≤ N := by
    exact ⟨ ⌊b⌋₊ + 1, fun x hx => Nat.succ_le_succ <| Nat.floor_mono hx.2 ⟩;
  -- Let $M$ be the maximum of $a_n$ and $1/a_n$ for $n \leq N$.
  obtain ⟨M, hM⟩ : ∃ M : ℝ, ∀ n ≤ N, (seq_a n ≤ M ∧ 1 / seq_a n ≤ M) := by
    use Max.max ( ∑ n ∈ Finset.range ( N + 1 ), seq_a n ) ( ∑ n ∈ Finset.range ( N + 1 ), 1 / seq_a n );
    exact fun n hn => ⟨ le_max_of_le_left <| Finset.single_le_sum ( fun n _ => le_of_lt <| seq_a_pos n ) <| Finset.mem_range.mpr <| by linarith, le_max_of_le_right <| Finset.single_le_sum ( fun n _ => le_of_lt <| one_div_pos.mpr <| seq_a_pos n ) <| Finset.mem_range.mpr <| by linarith ⟩;
  use M;
  intro x hx;
  rw [ abs_of_nonneg ( solution_f_pos x ( by linarith [ hx.1 ] ) |> le_of_lt ) ];
  unfold solution_f; aesop

/-
The function solution_f is integrable on any finite interval [a, b].
-/
lemma solution_f_intervalIntegrable (a b : ℝ) (ha : 0 ≤ a) (hab : a ≤ b) :
  IntervalIntegrable solution_f volume a b := by
  apply_rules [ MeasureTheory.IntegrableOn.intervalIntegrable ];
  -- The function $solution\_f$ is integrable on any finite interval because it is bounded and continuous.
  have h_integrable : MeasureTheory.IntegrableOn solution_f (Set.Icc a b) := by
    have h_bounded : ∃ M : ℝ, ∀ x ∈ Set.Icc a b, |solution_f x| ≤ M := by
      exact?
    norm_num +zetaDelta at *;
    refine' MeasureTheory.Integrable.mono' _ _ _;
    refine' fun x => h_bounded.choose;
    · norm_num;
    · refine' Measurable.aestronglyMeasurable _;
      refine' Measurable.ite _ _ _;
      · refine' measurableSet_lt _ _;
        · exact measurable_id;
        · fun_prop;
      · -- The function seq_a is measurable because it is a composition of measurable functions.
        have h_seq_a_measurable : Measurable seq_a := by
          exact?;
        exact h_seq_a_measurable.comp ( Measurable.add ( measurable_id'.nat_floor ) measurable_const );
      · fun_prop (disch := norm_num);
    · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with x hx using h_bounded.choose_spec x hx.1 hx.2;
  rwa [ Set.uIcc_of_le hab ]

/-
The integral of (f(x))^α over [n-1, n] is given by the formula involving a_n.
-/
lemma integral_solution_f_pow_on_interval (n : ℕ) (hn : n ≥ 1) (α : ℝ) :
  ∫ x in (n - 1 : ℝ)..n, (solution_f x) ^ α = (seq_a n) ^ α * (1 - (seq_a n) ^ 2) + (seq_a n) ^ (2 - α) := by
  unfold solution_f;
  -- We can split the integral into two parts: one over the interval where $f(x) = a_n$ and one over the interval where $f(x) = 1/a_n$.
  have h_integral_split : ∫ x in (n - 1 : ℝ)..n, (if x < n - (seq_a n)^2 then seq_a n else 1 / seq_a n) ^ α = (∫ x in (n - 1 : ℝ)..(n - (seq_a n)^2), seq_a n ^ α) + (∫ x in (n - (seq_a n)^2)..n, (1 / seq_a n) ^ α) := by
    have h_integral_split : ∫ x in (n - 1 : ℝ)..n, (if x < n - (seq_a n)^2 then seq_a n else 1 / seq_a n) ^ α = (∫ x in (n - 1 : ℝ)..(n - (seq_a n)^2), (if x < n - (seq_a n)^2 then seq_a n else 1 / seq_a n) ^ α) + (∫ x in (n - (seq_a n)^2)..n, (if x < n - (seq_a n)^2 then seq_a n else 1 / seq_a n) ^ α) := by
      rw [ intervalIntegral.integral_add_adjacent_intervals ];
      · apply_rules [ MeasureTheory.IntegrableOn.intervalIntegrable ];
        refine' MeasureTheory.Integrable.mono' _ _ _;
        refine' fun x => ( seq_a n ) ^ α + ( 1 / seq_a n ) ^ α;
        · exact Continuous.integrableOn_Icc ( by continuity );
        · exact Measurable.aestronglyMeasurable ( by exact Measurable.pow_const ( by exact Measurable.ite ( measurableSet_Iio ) measurable_const measurable_const ) _ );
        · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with x hx;
          split_ifs <;> norm_num;
          · rw [ abs_of_nonneg ( Real.rpow_nonneg ( le_of_lt ( seq_a_pos n ) ) _ ) ] ; exact le_add_of_nonneg_right ( Real.rpow_nonneg ( inv_nonneg.mpr ( le_of_lt ( seq_a_pos n ) ) ) _ );
          · rw [ abs_of_nonneg ( Real.rpow_nonneg ( inv_nonneg.mpr ( le_of_lt ( seq_a_pos n ) ) ) _ ) ] ; exact le_add_of_nonneg_left ( Real.rpow_nonneg ( le_of_lt ( seq_a_pos n ) ) _ );
      · rw [ intervalIntegrable_iff_integrableOn_Ioc_of_le ];
        · rw [ MeasureTheory.integrableOn_congr_fun ( fun x hx => by rw [ if_neg hx.1.not_lt ] ) measurableSet_Ioc ] ; norm_num;
        · exact sub_le_self _ ( sq_nonneg _ );
    convert h_integral_split using 2;
    · rw [ intervalIntegral.integral_of_le, intervalIntegral.integral_of_le ];
      · rw [ MeasureTheory.integral_Ioc_eq_integral_Ioo, MeasureTheory.integral_Ioc_eq_integral_Ioo ];
        exact MeasureTheory.setIntegral_congr_fun measurableSet_Ioo fun x hx => by rw [ if_pos hx.2 ] ;
      · gcongr;
        exact pow_le_one₀ ( by exact le_of_lt ( seq_a_pos n ) ) ( seq_a_le_one n );
      · gcongr;
        exact pow_le_one₀ ( by exact le_of_lt ( seq_a_pos n ) ) ( seq_a_le_one n );
    · rw [ intervalIntegral.integral_of_le, intervalIntegral.integral_of_le ] <;> norm_num;
      · rw [ MeasureTheory.setIntegral_congr_fun measurableSet_Ioc fun x hx => if_neg hx.1.not_lt ] ; norm_num;
      · positivity;
      · positivity;
  convert h_integral_split using 1;
  · rw [ intervalIntegral.integral_of_le, intervalIntegral.integral_of_le ] <;> norm_num;
    rw [ MeasureTheory.integral_Ioc_eq_integral_Ioo, MeasureTheory.integral_Ioc_eq_integral_Ioo ];
    refine' MeasureTheory.setIntegral_congr_fun measurableSet_Ioo fun x hx => _;
    norm_num [ show ⌊x⌋₊ = n - 1 from Nat.floor_eq_iff ( by linarith [ hx.1, show ( n : ℝ ) ≥ 1 by norm_cast ] ) |>.2 ⟨ by cases n <;> norm_num at * ; linarith, by cases n <;> norm_num at * ; linarith ⟩ ];
    rw [ Nat.sub_add_cancel hn ];
    rw [ Nat.cast_pred hn ] ; ring;
  · norm_num [ Real.rpow_sub ( seq_a_pos n ) ] ; ring;
    rw [ Real.inv_rpow ( le_of_lt ( seq_a_pos n ) ) ]

/-
The series sum(a_n) converges.
-/
lemma summable_seq_a : Summable seq_a := by
  unfold seq_a;
  rw [ ← summable_nat_add_iff 3 ];
  -- We will show that the integral of $\int_{3}^{\infty} \frac{1}{x (\log x)^2} dx$ converges.
  have h_integral_converges : Summable (fun n : ℕ => ∫ x in (n + 3 : ℝ)..((n + 4) : ℝ), (1 / (x * (Real.log x)^2))) := by
    -- We'll use the fact that the integral of $\frac{1}{x (\log x)^2}$ is $-\frac{1}{\log x}$.
    have h_integral_eval : ∀ a b : ℝ, 3 ≤ a → a < b → ∫ x in a..b, (1 / (x * (Real.log x) ^ 2)) = -1 / Real.log b + 1 / Real.log a := by
      intros; rw [ intervalIntegral.integral_eq_sub_of_hasDerivAt ];
      rotate_right;
      use fun x => -1 / Real.log x;
      · ring;
      · intro x hx; convert HasDerivAt.div ( hasDerivAt_const _ _ ) ( Real.hasDerivAt_log ( show x ≠ 0 by cases Set.mem_uIcc.mp hx <;> linarith ) ) ( ne_of_gt <| Real.log_pos <| show x > 1 by cases Set.mem_uIcc.mp hx <;> linarith ) using 1 ; ring;
      · apply_rules [ ContinuousOn.intervalIntegrable ];
        exact continuousOn_of_forall_continuousAt fun x hx => ContinuousAt.div continuousAt_const ( ContinuousAt.mul continuousAt_id <| ContinuousAt.pow ( Real.continuousAt_log <| by cases Set.mem_uIcc.mp hx <;> linarith ) _ ) <| ne_of_gt <| mul_pos ( by cases Set.mem_uIcc.mp hx <;> linarith ) <| sq_pos_of_pos <| Real.log_pos <| by cases Set.mem_uIcc.mp hx <;> linarith;
    -- We can use the fact that the series $\sum_{n=3}^{\infty} \left( \frac{1}{\log n} - \frac{1}{\log (n+1)} \right)$ is a telescoping series.
    have h_telescoping : ∀ N : ℕ, ∑ n ∈ Finset.range N, (∫ x in (n + 3 : ℝ)..((n + 4) : ℝ), 1 / (x * (Real.log x) ^ 2)) = 1 / Real.log 3 - 1 / Real.log (N + 3) := by
      intro N; induction N <;> simp_all +decide [ Finset.sum_range_succ ] ; ring;
      have := h_integral_eval ( 3 + ( ↑‹ℕ› : ℝ ) ) ( 4 + ( ↑‹ℕ› : ℝ ) ) ( by linarith ) ( by linarith ) ; norm_num at * ; ring_nf at * ; linarith;
    rw [ summable_iff_not_tendsto_nat_atTop_of_nonneg ];
    · exact fun h => absurd ( h.congr h_telescoping ) ( by exact not_tendsto_atTop_of_tendsto_nhds <| by simpa using tendsto_const_nhds.sub <| tendsto_inv_atTop_zero.comp <| Real.tendsto_log_atTop.comp <| Filter.tendsto_atTop_add_const_right _ _ tendsto_natCast_atTop_atTop );
    · exact fun n => intervalIntegral.integral_nonneg ( by linarith ) fun x hx => one_div_nonneg.2 ( mul_nonneg ( by linarith [ hx.1 ] ) ( sq_nonneg _ ) );
  -- By comparison, it suffices to show that the integral of $\frac{1}{x (\log x)^2}$ over $[n+3, n+4]$ is bounded above by $\frac{1}{(n+3) (\log (n+3))^2}$.
  have h_integral_bound : ∀ n : ℕ, ∫ x in (n + 3 : ℝ)..((n + 4) : ℝ), (1 / (x * (Real.log x)^2)) ≥ (1 / ((n + 4 : ℝ) * (Real.log (n + 4))^2)) := by
    intros n
    have h_integral_bound : ∫ x in (n + 3 : ℝ)..((n + 4) : ℝ), (1 / (x * (Real.log x)^2)) ≥ ∫ x in (n + 3 : ℝ)..((n + 4) : ℝ), (1 / ((n + 4 : ℝ) * (Real.log (n + 4))^2)) := by
      refine' intervalIntegral.integral_mono_on _ _ _ _ <;> norm_num;
      · apply_rules [ ContinuousOn.intervalIntegrable ];
        exact continuousOn_of_forall_continuousAt fun x hx => ContinuousAt.mul ( ContinuousAt.inv₀ ( ContinuousAt.pow ( Real.continuousAt_log ( by cases Set.mem_uIcc.mp hx <;> linarith ) ) _ ) ( ne_of_gt ( sq_pos_of_pos ( Real.log_pos ( by cases Set.mem_uIcc.mp hx <;> linarith ) ) ) ) ) ( ContinuousAt.inv₀ ( continuousAt_id ) ( ne_of_gt ( by cases Set.mem_uIcc.mp hx <;> linarith ) ) );
      · bound;
    norm_num at * ; linarith;
  exact summable_nat_add_iff 1 |>.1 <| h_integral_converges.of_nonneg_of_le ( fun n => by positivity ) ( fun n => by exact_mod_cast h_integral_bound n )

/-
The integral of solution_f from 0 to infinity converges. This corresponds to the case α = 1.
-/
lemma integral_solution_f_converges : ∃ L, Tendsto (λ b ↦ ∫ x in 0..b, solution_f x) atTop (𝓝 L) := by
  -- We'll use the fact that if the integral of $f$ over $[0, b]$ is bounded and converges as $b$ approaches infinity, then the limit of the integral over $[0, b]$ as $b$ approaches infinity is the integral over $[0, \infty)$.
  have h_bounded : ∀ b : ℝ, 0 ≤ b → ∫ x in (0 : ℝ)..b, solution_f x ≤ ∑' n : ℕ, (seq_a (n + 1)) + ∑' n : ℕ, (seq_a (n + 1)) ^ (2 - 1) := by
    intros b hb
    have h_integral_bound : ∫ x in (0 : ℝ)..b, solution_f x ≤ ∑ n ∈ Finset.range (Nat.floor b + 1), (∫ x in (n : ℝ)..(n + 1), solution_f x) := by
      -- The integral over $[0, b]$ can be split into the sum of integrals over $[n, n+1]$ for $n = 0, 1, \ldots, \lfloor b \rfloor$.
      have h_split : ∫ x in (0 : ℝ)..b, solution_f x ≤ ∫ x in (0 : ℝ)..(Nat.floor b + 1), solution_f x := by
        apply_rules [ intervalIntegral.integral_mono_interval ];
        · norm_num;
        · linarith [ Nat.lt_floor_add_one b ];
        · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with x hx using le_of_lt ( solution_f_pos x hx.1.le );
        · apply_rules [ solution_f_intervalIntegrable ] ; linarith [ Nat.lt_floor_add_one b ] ;
          positivity;
      convert h_split using 1;
      convert intervalIntegral.sum_integral_adjacent_intervals _ <;> norm_num;
      exact fun k hk => solution_f_intervalIntegrable _ _ ( by positivity ) ( by linarith );
    -- By definition of $solution_f$, we know that $\int_{n}^{n+1} solution_f(x) \, dx = a_{n+1} (1 - a_{n+1}^2) + a_{n+1}^{2 - 1}$.
    have h_integral_def : ∀ n : ℕ, ∫ x in (n : ℝ)..(n + 1), solution_f x = (seq_a (n + 1)) * (1 - (seq_a (n + 1))^2) + (seq_a (n + 1)) ^ (2 - 1) := by
      intro n; convert integral_solution_f_pow_on_interval ( n + 1 ) ( by linarith ) 1 using 1 <;> norm_num;
    have h_sum_bound : ∑ n ∈ Finset.range (Nat.floor b + 1), (seq_a (n + 1)) * (1 - (seq_a (n + 1))^2) ≤ ∑' n : ℕ, (seq_a (n + 1)) := by
      have h_sum_bound : ∀ n : ℕ, (seq_a (n + 1)) * (1 - (seq_a (n + 1))^2) ≤ (seq_a (n + 1)) := by
        exact fun n => mul_le_of_le_one_right ( le_of_lt ( seq_a_pos _ ) ) ( sub_le_self _ ( sq_nonneg _ ) );
      exact le_trans ( Finset.sum_le_sum fun _ _ => h_sum_bound _ ) ( Summable.sum_le_tsum ( Finset.range ( ⌊b⌋₊ + 1 ) ) ( fun _ _ => seq_a_pos _ |> le_of_lt ) ( by simpa using summable_nat_add_iff 1 |>.2 <| summable_seq_a ) );
    have h_sum_bound : ∑ n ∈ Finset.range (Nat.floor b + 1), (seq_a (n + 1)) ^ (2 - 1) ≤ ∑' n : ℕ, (seq_a (n + 1)) ^ (2 - 1) := by
      norm_num;
      exact Summable.sum_le_tsum ( Finset.range ( ⌊b⌋₊ + 1 ) ) ( fun _ _ => le_of_lt ( seq_a_pos _ ) ) ( by simpa using summable_nat_add_iff 1 |>.2 <| summable_seq_a );
    simp_all +decide [ Finset.sum_add_distrib ];
    linarith;
  have h_monotone : MonotoneOn (fun b => ∫ x in (0 : ℝ)..b, solution_f x) (Set.Ici 0) := by
    intro a ha b hb hab; apply_rules [ intervalIntegral.integral_mono_interval, zero_le_one ] ; aesop;
    · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with x hx using le_of_lt ( solution_f_pos x hx.1.le );
    · apply_rules [ solution_f_intervalIntegrable ] ; aesop;
  have h_converge : Filter.Tendsto (fun b : ℝ => ∫ x in (0 : ℝ)..b, solution_f x) Filter.atTop (nhds (sSup (Set.image (fun b => ∫ x in (0 : ℝ)..b, solution_f x) (Set.Ici 0)))) := by
    apply_rules [ tendsto_order.2 ⟨ _, _ ⟩ ];
    · intro a ha;
      contrapose! ha;
      exact csSup_le ( Set.Nonempty.image _ <| Set.nonempty_Ici ) <| Set.forall_mem_image.2 fun x hx => le_of_not_gt fun hx' => ha <| Filter.eventually_atTop.2 ⟨ x, fun y hy => hx'.trans_le <| h_monotone hx ( show 0 ≤ y by linarith [ Set.mem_Ici.1 hx ] ) hy ⟩;
    · exact fun x hx => Filter.eventually_atTop.mpr ⟨ 0, fun y hy => lt_of_le_of_lt ( le_csSup ( show BddAbove ( ( fun b => ∫ x in ( 0 : ℝ )..b, solution_f x ) '' Set.Ici 0 ) from ⟨ _, Set.forall_mem_image.mpr fun b hb => h_bounded b hb ⟩ ) <| Set.mem_image_of_mem _ hy ) hx ⟩;
  exact ⟨ _, h_converge ⟩

/-
The series sum((a_n)^β) diverges if β < 1.
-/
lemma not_summable_seq_a_pow_of_lt_one (β : ℝ) (hβ : β < 1) : ¬ Summable (fun n => (seq_a n) ^ β) := by
  -- By comparison, it suffices to show that $\sum_{n=3}^{\infty} \frac{1}{n^{\beta} (\log n)^{2\beta}}$ diverges.
  suffices h_comp : ¬ Summable (fun n : ℕ => 1 / (n : ℝ) ^ β * (1 / (Real.log n) ^ (2 * β))) by
    -- Since $seq_a n = \frac{1}{n (\log n)^2}$ for $n \geq 3$, we have $(seq_a n)^\beta = \frac{1}{n^\beta (\log n)^{2\beta}}$ for $n \geq 3$.
    have h_eq : ∀ n ≥ 3, (seq_a n) ^ β = 1 / (n : ℝ) ^ β * (1 / (Real.log n) ^ (2 * β)) := by
      intros n hn
      have h_eq : seq_a n = 1 / (n * (Real.log n)^2) := by
        exact if_neg ( by linarith );
      rw [ h_eq, Real.div_rpow ] <;> norm_num;
      · rw [ Real.mul_rpow ( by positivity ) ( by positivity ), ← Real.rpow_natCast, ← Real.rpow_mul ( by positivity ) ] ; ring;
      · positivity;
    rw [ ← summable_nat_add_iff 3 ] at * ; aesop;
  -- Since $\beta < 1$, we have $(Real.log n)^{2\beta} \leq n^{1-\beta}$ for sufficiently large $n$.
  have h_log_bound : ∃ N : ℕ, ∀ n ≥ N, (Real.log n) ^ (2 * β) ≤ n ^ (1 - β) := by
    -- Taking the logarithm of both sides, we need to show that $2\beta \log(\log n) \leq (1 - \beta) \log n$ for sufficiently large $n$.
    suffices h_log_bound : ∃ N : ℕ, ∀ n ≥ N, 2 * β * Real.log (Real.log n) ≤ (1 - β) * Real.log n by
      obtain ⟨ N, hN ⟩ := h_log_bound;
      use N + 3; intro n hn; rw [ Real.rpow_def_of_pos ( Real.log_pos <| by norm_cast; linarith ), Real.rpow_def_of_pos ( by norm_cast; linarith ) ] ; norm_num ; linarith [ hN n <| by linarith ] ;
    -- We can divide both sides by $\log n$ (which is positive for $n \geq 3$) to get $2\beta \frac{\log(\log n)}{\log n} \leq 1 - \beta$.
    suffices h_div_bound : ∃ N : ℕ, ∀ n ≥ N, 2 * β * (Real.log (Real.log n) / Real.log n) ≤ 1 - β by
      obtain ⟨ N, hN ⟩ := h_div_bound; use N + 3; intro n hn; have := hN n ( by linarith ) ; rw [ mul_div, div_le_iff₀ ] at this <;> nlinarith [ Real.log_pos <| show ( n :ℝ ) > 1 by norm_cast; linarith ] ;
    -- We know that $\frac{\log(\log n)}{\log n}$ tends to $0$ as $n$ tends to infinity.
    have h_log_log_div_log_zero : Filter.Tendsto (fun n : ℕ => Real.log (Real.log n) / Real.log n) Filter.atTop (nhds 0) := by
      -- Let $y = \log n$, therefore the limit becomes $\lim_{y \to \infty} \frac{\log y}{y}$.
      suffices h_log_y : Filter.Tendsto (fun y : ℝ => Real.log y / y) Filter.atTop (nhds 0) by
        exact h_log_y.comp ( Real.tendsto_log_atTop.comp tendsto_natCast_atTop_atTop );
      -- Let $z = \frac{1}{y}$, therefore the limit becomes $\lim_{z \to 0^+} z \log \left(\frac{1}{z}\right)$.
      suffices h_log_recip : Filter.Tendsto (fun z : ℝ => z * Real.log (1 / z)) (Filter.map (fun y => 1 / y) Filter.atTop) (nhds 0) by
        exact h_log_recip.congr ( by simp +contextual [ div_eq_inv_mul ] );
      norm_num;
      exact tendsto_nhdsWithin_of_tendsto_nhds ( by simpa using Real.continuous_mul_log.neg.tendsto 0 );
    simpa using h_log_log_div_log_zero.const_mul ( 2 * β ) |> fun h => h.eventually ( ge_mem_nhds <| by linarith );
  -- Using the bound, we can show that $\frac{1}{n^{\beta} (\log n)^{2\beta}} \geq \frac{1}{n}$ for sufficiently large $n$.
  obtain ⟨N, hN⟩ : ∃ N : ℕ, ∀ n ≥ N, (1 / (n : ℝ) ^ β * (1 / (Real.log n) ^ (2 * β))) ≥ (1 / (n : ℝ)) := by
    field_simp;
    obtain ⟨ N, hN ⟩ := h_log_bound; use N + 2; intro n hn; rw [ div_le_div_iff₀ ] <;> norm_num;
    · exact le_trans ( mul_le_mul_of_nonneg_left ( hN n ( by linarith ) ) ( by positivity ) ) ( by rw [ ← Real.rpow_add ( by norm_cast; linarith ) ] ; norm_num [ show β + ( 1 - β ) = 1 by ring ] );
    · linarith;
    · exact mul_pos ( Real.rpow_pos_of_pos ( by norm_cast; linarith ) _ ) ( Real.rpow_pos_of_pos ( Real.log_pos ( by norm_cast; linarith ) ) _ );
  -- Since $\sum_{n=N}^{\infty} \frac{1}{n}$ diverges, it follows that $\sum_{n=N}^{\infty} \frac{1}{n^{\beta} (\log n)^{2\beta}}$ also diverges.
  have h_div : ¬ Summable (fun n : ℕ => (1 / (n : ℝ))) := by
    simpa using Real.not_summable_natCast_inv;
  rw [ ← summable_nat_add_iff N ] at *;
  exact fun h => h_div <| h.of_nonneg_of_le ( fun n => by positivity ) fun n => hN _ <| by linarith;

/-
If α > 1, the integral of (f(x))^α diverges.
-/
lemma integral_diverges_of_alpha_gt_one (α : ℝ) (hα : 1 < α) :
  ¬∃ (L : ℝ), Tendsto (λ b ↦ ∫ x in 0..b, (solution_f x) ^ α) atTop (𝓝 L) := by
  -- By the lemma, $\int_0^\infty (f(x))^\alpha \, dx$ diverges if $\alpha \geq 1$.
  intro h_contra
  obtain ⟨L, hL⟩ := h_contra
  have h_diverge : Filter.Tendsto (fun b => ∫ x in (0 : ℝ)..b, (solution_f x) ^ α) Filter.atTop Filter.atTop := by
    -- By the properties of the integral, we can break the integral up into a sum of integrals over each interval $[n-1, n]$.
    have h_integral_split : ∀ N : ℕ, N ≥ 3 → ∫ x in (0 : ℝ)..N, (solution_f x) ^ α ≥ ∑ n ∈ Finset.Icc 3 N, (seq_a n) ^ α * (1 - (seq_a n) ^ 2) + ∑ n ∈ Finset.Icc 3 N, (seq_a n) ^ (2 - α) := by
      -- By the properties of the integral, we can break the integral up into a sum of integrals over each interval $[n-1, n]$ and apply the result from `integral_solution_f_pow_on_interval`.
      intros N hN
      have h_integral_split : ∫ x in (0 : ℝ)..N, (solution_f x) ^ α = ∑ n ∈ Finset.Icc 1 N, ∫ x in (n - 1 : ℝ)..n, (solution_f x) ^ α := by
        erw [ Finset.sum_Ico_eq_sum_range ];
        symm;
        convert intervalIntegral.sum_integral_adjacent_intervals _ <;> norm_num;
        · ring;
        · intro k hk; apply_rules [ MeasureTheory.IntegrableOn.intervalIntegrable ];
          have h_integrable : MeasureTheory.IntegrableOn (fun x => solution_f x ^ α) (Set.Icc (k : ℝ) (k + 1)) := by
            have h_bounded : ∃ M : ℝ, ∀ x ∈ Set.Icc (k : ℝ) (k + 1), |solution_f x ^ α| ≤ M := by
              have := solution_f_bounded_on_Icc ( k : ℝ ) ( k + 1 ) ( by positivity ) ( by linarith );
              obtain ⟨ M, hM ⟩ := this;
              use M ^ α;
              exact fun x hx => by simpa only [ abs_of_nonneg ( Real.rpow_nonneg ( abs_nonneg _ ) _ ) ] using Real.abs_rpow_le_abs_rpow _ _ |> le_trans <| Real.rpow_le_rpow ( abs_nonneg _ ) ( hM x hx ) <| by positivity;
            refine' MeasureTheory.Integrable.mono' _ _ _;
            refine' fun x => h_bounded.choose;
            · norm_num;
            · refine' Measurable.aestronglyMeasurable _;
              refine' Measurable.pow_const _ _;
              refine' Measurable.ite _ _ _;
              · refine' measurableSet_lt _ _;
                · exact measurable_id;
                · fun_prop (disch := norm_num);
              · exact Measurable.comp ( show Measurable fun n : ℕ => seq_a n from by exact Measurable.of_discrete ) ( show Measurable fun x : ℝ => ⌊x⌋₊ + 1 from by exact Measurable.add ( measurable_id'.nat_floor ) measurable_const );
              · refine' Measurable.div _ _ <;> norm_num;
                exact Measurable.comp ( show Measurable fun n : ℕ => seq_a n from by exact Measurable.ite ( by measurability ) ( by measurability ) ( by measurability ) ) ( Nat.measurable_floor.comp measurable_id' |> Measurable.add <| measurable_const );
            · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with x hx using h_bounded.choose_spec x hx;
          rwa [ Set.uIcc_of_le ( by norm_num ) ];
      rw [ h_integral_split, ← Finset.sum_add_distrib, Finset.sum_congr rfl fun n hn => integral_solution_f_pow_on_interval n ( by linarith [ Finset.mem_Icc.mp hn ] ) α ];
      exact Finset.sum_le_sum_of_subset_of_nonneg ( Finset.Icc_subset_Icc ( by norm_num ) le_rfl ) fun _ _ _ => add_nonneg ( mul_nonneg ( Real.rpow_nonneg ( le_of_lt ( seq_a_pos _ ) ) _ ) ( sub_nonneg.2 ( pow_le_one₀ ( le_of_lt ( seq_a_pos _ ) ) ( seq_a_le_one _ ) ) ) ) ( Real.rpow_nonneg ( le_of_lt ( seq_a_pos _ ) ) _ );
    -- Since $\sum_{n=3}^\infty (a_n)^{2-\alpha}$ diverges, the integral $\int_0^\infty (f(x))^\alpha \, dx$ also diverges.
    have h_sum_diverge : Filter.Tendsto (fun N : ℕ => ∑ n ∈ Finset.Icc 3 N, (seq_a n) ^ (2 - α)) Filter.atTop Filter.atTop := by
      have h_sum_diverge : ¬ Summable (fun n : ℕ => (seq_a n) ^ (2 - α)) := by
        have := not_summable_seq_a_pow_of_lt_one ( 2 - α ) ( by linarith ) ; aesop;
      have h_sum_diverge : Filter.Tendsto (fun N : ℕ => ∑ n ∈ Finset.range (N - 2), (seq_a (n + 3)) ^ (2 - α)) Filter.atTop Filter.atTop := by
        exact not_summable_iff_tendsto_nat_atTop_of_nonneg ( fun _ => Real.rpow_nonneg ( le_of_lt ( seq_a_pos _ ) ) _ ) |>.1 ( by exact_mod_cast mt ( summable_nat_add_iff 3 |>.1 ) h_sum_diverge ) |> Filter.Tendsto.comp <| Filter.tendsto_sub_atTop_nat 2;
      exact h_sum_diverge.congr' ( by filter_upwards [ Filter.eventually_ge_atTop 3 ] with N hN using by erw [ Finset.sum_Ico_eq_sum_range ] ; ac_rfl );
    have h_integral_diverge : Filter.Tendsto (fun N : ℕ => ∫ x in (0 : ℝ)..N, (solution_f x) ^ α) Filter.atTop Filter.atTop := by
      refine' Filter.tendsto_atTop_mono' _ _ h_sum_diverge;
      filter_upwards [ Filter.eventually_ge_atTop 3 ] with N hN using le_trans ( le_add_of_nonneg_left <| Finset.sum_nonneg fun _ _ => mul_nonneg ( Real.rpow_nonneg ( le_of_lt <| seq_a_pos _ ) _ ) <| sub_nonneg.2 <| pow_le_one₀ ( le_of_lt <| seq_a_pos _ ) <| seq_a_le_one _ ) ( h_integral_split N hN );
    exact False.elim <| not_tendsto_atTop_of_tendsto_nhds ( hL.comp <| tendsto_natCast_atTop_atTop ) h_integral_diverge;
  exact not_tendsto_atTop_of_tendsto_nhds hL h_diverge

/-
The series sum((a_n)^p) converges for p >= 1.
-/
lemma summable_seq_a_pow {p : ℝ} (hp : 1 ≤ p) : Summable (fun n => (seq_a n) ^ p) := by
  -- Since $p \geq 1$, we can use the fact that $(a_n)^p \leq a_n$ for all $n \geq 3$.
  have h_bound : ∀ n ≥ 3, (seq_a n) ^ p ≤ seq_a n := by
    intro n hn;
    exact le_trans ( Real.rpow_le_rpow_of_exponent_ge ( seq_a_pos n ) ( seq_a_le_one n ) hp ) ( by norm_num );
  rw [ ← summable_nat_add_iff 3 ];
  exact Summable.of_nonneg_of_le ( fun n => Real.rpow_nonneg ( le_of_lt ( seq_a_pos _ ) ) _ ) ( fun n => h_bound _ ( by linarith ) ) ( summable_nat_add_iff 3 |>.2 <| by exact? )

/-
If α < 1, the integral of (f(x))^α diverges.
-/
lemma integral_diverges_of_alpha_lt_one (α : ℝ) (hα : α < 1) :
  ¬∃ (L : ℝ), Tendsto (λ b ↦ ∫ x in 0..b, (solution_f x) ^ α) atTop (𝓝 L) := by
  -- Assume by contradiction that the integral converges.
  by_contra h_contra
  obtain ⟨L, hL⟩ := h_contra

  -- Since α < 1, the series sum((a_n)^α) diverges.
  have h_sum_diverges : ¬ Summable (fun n => (seq_a n) ^ α) := by
    exact?;
  -- Using the integral_split lemma, we can express the integral from 0 to N as a sum of integrals over each interval [n-1, n].
  have h_integral_sum : ∀ N : ℕ, N ≥ 1 → ∫ x in (0 : ℝ)..N, (solution_f x) ^ α = ∑ n ∈ Finset.range N, ((seq_a (n + 1)) ^ α * (1 - (seq_a (n + 1)) ^ 2) + (seq_a (n + 1)) ^ (2 - α)) := by
    intro N hN;
    have h_integral_split : ∀ n : ℕ, n ≥ 1 → ∫ x in (n - 1 : ℝ)..n, (solution_f x) ^ α = (seq_a n) ^ α * (1 - (seq_a n) ^ 2) + (seq_a n) ^ (2 - α) := by
      exact?;
    rw [ ← Finset.sum_congr rfl fun n hn => h_integral_split ( n + 1 ) ( by linarith [ Finset.mem_range.mp hn ] ) ];
    symm;
    convert intervalIntegral.sum_integral_adjacent_intervals _ <;> norm_num;
    intro k hk;
    have := h_integral_split ( k + 1 ) ( by linarith );
    contrapose! this;
    rw [ intervalIntegral.integral_undef ] <;> norm_num [ this ];
    refine' ne_of_lt ( add_pos_of_nonneg_of_pos ( mul_nonneg ( Real.rpow_nonneg ( le_of_lt ( seq_a_pos _ ) ) _ ) ( sub_nonneg.mpr _ ) ) ( Real.rpow_pos_of_pos ( seq_a_pos _ ) _ ) );
    exact pow_le_one₀ ( le_of_lt ( seq_a_pos _ ) ) ( seq_a_le_one _ );
  -- Since the series sum((a_n)^α) diverges, the partial sums of the series also diverge.
  have h_partial_sums_diverge : Filter.Tendsto (fun N : ℕ => ∑ n ∈ Finset.range N, (seq_a (n + 1)) ^ α * (1 - (seq_a (n + 1)) ^ 2) + ∑ n ∈ Finset.range N, (seq_a (n + 1)) ^ (2 - α)) Filter.atTop Filter.atTop := by
    -- Since $a_n \to 0$, we have $1 - a_n^2 \to 1$. Therefore, for large $n$, $a_n^\alpha (1 - a_n^2) \geq \frac{1}{2} a_n^\alpha$.
    have h_bound : ∃ N₀ : ℕ, ∀ n ≥ N₀, (seq_a (n + 1)) ^ α * (1 - (seq_a (n + 1)) ^ 2) ≥ (1 / 2) * (seq_a (n + 1)) ^ α := by
      have h_bound : Filter.Tendsto (fun n : ℕ => (seq_a (n + 1)) ^ 2) Filter.atTop (nhds 0) := by
        have h_a_n_sq_zero : Filter.Tendsto (fun n : ℕ => seq_a n ^ 2) Filter.atTop (nhds 0) := by
          simpa using Filter.Tendsto.pow ( seq_a_tendsto_zero ) 2;
        exact h_a_n_sq_zero.comp ( Filter.tendsto_add_atTop_nat 1 );
      exact Filter.eventually_atTop.mp ( h_bound.eventually ( gt_mem_nhds <| show 0 < 1 / 2 by norm_num ) ) |> fun ⟨ N₀, hN₀ ⟩ ↦ ⟨ N₀, fun n hn ↦ by nlinarith [ hN₀ n hn, show 0 < seq_a ( n + 1 ) ^ α from Real.rpow_pos_of_pos ( seq_a_pos _ ) _ ] ⟩;
    -- Since the series sum((a_n)^α) diverges, the partial sums of the series also diverge. Therefore, the partial sums of the series sum((a_n)^α * (1 - a_n^2)) also diverge.
    have h_partial_sums_diverge : Filter.Tendsto (fun N : ℕ => ∑ n ∈ Finset.range N, (seq_a (n + 1)) ^ α * (1 - (seq_a (n + 1)) ^ 2)) Filter.atTop Filter.atTop := by
      have h_partial_sums_diverge : Filter.Tendsto (fun N : ℕ => ∑ n ∈ Finset.range N, (1 / 2) * (seq_a (n + 1)) ^ α) Filter.atTop Filter.atTop := by
        exact not_summable_iff_tendsto_nat_atTop_of_nonneg ( fun _ => mul_nonneg ( by norm_num ) ( Real.rpow_nonneg ( le_of_lt ( seq_a_pos _ ) ) _ ) ) |>.1 ( by simpa [ summable_mul_left_iff ] using mt ( summable_nat_add_iff 1 |>.1 ) h_sum_diverges );
      obtain ⟨ N₀, hN₀ ⟩ := h_bound;
      have h_partial_sums_diverge : Filter.Tendsto (fun N : ℕ => ∑ n ∈ Finset.range N, (seq_a (n + 1)) ^ α * (1 - (seq_a (n + 1)) ^ 2)) Filter.atTop Filter.atTop := by
        have h_partial_sums_diverge : ∀ N ≥ N₀, ∑ n ∈ Finset.range N, (seq_a (n + 1)) ^ α * (1 - (seq_a (n + 1)) ^ 2) ≥ ∑ n ∈ Finset.range N₀, (seq_a (n + 1)) ^ α * (1 - (seq_a (n + 1)) ^ 2) + ∑ n ∈ Finset.Ico N₀ N, (1 / 2) * (seq_a (n + 1)) ^ α := by
          intro N hN; rw [ ← Finset.sum_range_add_sum_Ico _ hN ] ; exact add_le_add_left ( Finset.sum_le_sum fun n hn => hN₀ n <| Finset.mem_Ico.mp hn |>.1 ) _;
        have h_partial_sums_diverge : Filter.Tendsto (fun N : ℕ => ∑ n ∈ Finset.Ico N₀ N, (1 / 2) * (seq_a (n + 1)) ^ α) Filter.atTop Filter.atTop := by
          have h_partial_sums_diverge : Filter.Tendsto (fun N : ℕ => ∑ n ∈ Finset.range N, (1 / 2) * (seq_a (n + 1)) ^ α - ∑ n ∈ Finset.range N₀, (1 / 2) * (seq_a (n + 1)) ^ α) Filter.atTop Filter.atTop := by
            exact Filter.tendsto_atTop_add_const_right _ _ ‹_›;
          exact h_partial_sums_diverge.congr' ( by filter_upwards [ Filter.eventually_ge_atTop N₀ ] with N hN using by rw [ Finset.sum_Ico_eq_sub _ hN ] );
        rw [ Filter.tendsto_atTop_atTop ] at *;
        exact fun b => by obtain ⟨ i, hi ⟩ := h_partial_sums_diverge ( b - ∑ n ∈ Finset.range N₀, seq_a ( n + 1 ) ^ α * ( 1 - seq_a ( n + 1 ) ^ 2 ) ) ; exact ⟨ Max.max N₀ i, fun n hn => by linarith [ hi n ( le_trans ( le_max_right _ _ ) hn ), ‹∀ N ≥ N₀, ∑ n ∈ Finset.range N, seq_a ( n + 1 ) ^ α * ( 1 - seq_a ( n + 1 ) ^ 2 ) ≥ ∑ n ∈ Finset.range N₀, seq_a ( n + 1 ) ^ α * ( 1 - seq_a ( n + 1 ) ^ 2 ) + ∑ n ∈ Finset.Ico N₀ N, 1 / 2 * seq_a ( n + 1 ) ^ α› n ( le_trans ( le_max_left _ _ ) hn ) ] ⟩ ;
      convert h_partial_sums_diverge using 1;
    exact Filter.tendsto_atTop_mono ( fun N => le_add_of_nonneg_right <| Finset.sum_nonneg fun _ _ => Real.rpow_nonneg ( le_of_lt <| seq_a_pos _ ) _ ) h_partial_sums_diverge;
  simp_all +decide [ Finset.sum_add_distrib ];
  exact not_tendsto_atTop_of_tendsto_nhds ( hL.comp tendsto_natCast_atTop_atTop ) ( Filter.Tendsto.congr' ( by filter_upwards [ Filter.eventually_ge_atTop 1 ] with N hN; aesop ) h_partial_sums_diverge )

/-
The function solution_f satisfies all conditions of Polya-Szego Problem 114.1.
-/
theorem problem_114_1_solution : 
    (∀ x ≥ 0, solution_f x > 0) ∧ 
    (∀ (a b : ℝ), 0 ≤ a → a ≤ b → ∃ M : ℝ, ∀ x ∈ Set.Icc a b, |solution_f x| ≤ M) ∧
    (∀ (a b : ℝ), 0 ≤ a → a ≤ b → IntervalIntegrable solution_f volume a b) ∧
    (∃ (L : ℝ), Tendsto (λ b ↦ ∫ x in 0..b, solution_f x) atTop (𝓝 L)) ∧
    (∀ (α : ℝ), α ≠ 1 → ¬∃ (L : ℝ), Tendsto (λ b ↦ ∫ x in 0..b, (solution_f x) ^ α) atTop (𝓝 L)) := by
  refine' ⟨ _, _, _, _, _ ⟩
  · exact solution_f_pos
  · exact solution_f_bounded_on_Icc
  · exact solution_f_intervalIntegrable
  · exact integral_solution_f_converges
  · intro α hα
    rcases lt_trichotomy α 1 with h | h | h
    · exact integral_diverges_of_alpha_lt_one α h
    · contradiction
    · exact integral_diverges_of_alpha_gt_one α h