/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: bbcfa22a-5d2f-4674-93a5-f24feba3b5cb
-/

/-
We formalized and proved Polya-Szego Problem 119.
The problem states that for an everywhere convergent power series (entire function) which is not a polynomial, the central subscript v(x) (the index of the maximum term) tends to infinity as |x| tends to infinity.

We defined the coefficients of the power series using `iteratedDeriv` and `factorial`.
We proved two helper lemmas:
1. `infinite_nonzero_coeffs`: An entire function that is not a polynomial has infinitely many non-zero Taylor coefficients.
2. `dominance_of_higher_term`: For any M and any N > M with non-zero coefficient a_N, for sufficiently large x, the term |a_N x^N| dominates all terms |a_k x^k| with k <= M.

Using these lemmas, we proved the main theorem `problem_119`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Complex
open Real
open Filter
open Topology

/-
If a_N is non-zero and N > M, then for sufficiently large x, the term |a_N x^N| dominates |a_k x^k| for all k <= M.
-/
lemma dominance_of_higher_term (a : ℕ → ℂ) (M N : ℕ) (hNM : M < N) (haN : a N ≠ 0) :
    ∃ R : ℝ, ∀ x > R, ∀ k ≤ M, ‖a k * (x : ℂ) ^ k‖ < ‖a N * (x : ℂ) ^ N‖ := by
  simp_all +decide [ abs_mul ];
  -- For each $k \leq M$, we have $\frac{|a_k|}{|a_N|} < x^{N-k}$ for sufficiently large $x$.
  have h_bound : ∀ k ≤ M, ∃ R : ℝ, ∀ x > R, ‖a k‖ < ‖a N‖ * abs x ^ (N - k) := by
    intro k hk;
    -- Since $N > k$, we have $N - k > 0$, and thus $|x|^{N - k} \to \infty$ as $x \to \infty$.
    have h_exp : Filter.Tendsto (fun x : ℝ => ‖a N‖ * abs x ^ (N - k)) Filter.atTop Filter.atTop := by
      exact Filter.Tendsto.const_mul_atTop ( norm_pos_iff.mpr haN ) ( Filter.tendsto_pow_atTop ( Nat.sub_ne_zero_of_lt ( by linarith ) ) |> Filter.Tendsto.comp <| Filter.tendsto_abs_atTop_atTop );
    exact Filter.eventually_atTop.mp ( h_exp.eventually_gt_atTop ‖a k‖ ) |> fun ⟨ R, hR ⟩ ↦ ⟨ R, fun x hx ↦ hR x hx.le ⟩;
  -- Let $R$ be the maximum of the $R_k$'s from the bound.
  obtain ⟨R, hR⟩ : ∃ R : ℝ, ∀ k ≤ M, ∀ x : ℝ, x > R → ‖a k‖ < ‖a N‖ * abs x ^ (N - k) := by
    choose! R hR using h_bound ; exact ⟨ ∑ k ∈ Finset.Iic M, |R k|, fun k hk x hx => hR k hk x <| by cases abs_cases ( R k ) <;> linarith [ Finset.single_le_sum ( fun k _ => abs_nonneg ( R k ) ) ( Finset.mem_Iic.mpr hk ) ] ⟩ ;
  refine' ⟨ Max.max R 1, fun x hx k hk => _ ⟩;
  convert mul_lt_mul_of_pos_right ( hR k hk x ( lt_of_le_of_lt ( le_max_left _ _ ) hx ) ) ( pow_pos ( abs_pos.mpr ( by linarith [ le_max_right R 1 ] ) ) k ) using 1 ; rw [ mul_assoc, ← pow_add, Nat.sub_add_cancel ( by linarith ) ]

/-
If an entire function is not a polynomial, then it has infinitely many non-zero derivatives at 0.
-/
lemma infinite_nonzero_coeffs (f : ℂ → ℂ) (hf : AnalyticOn ℂ f ⊤)
    (hpoly : ¬∃ (p : Polynomial ℂ), ∀ z, f z = p.eval z) :
    ∀ M : ℕ, ∃ n > M, iteratedDeriv n f 0 ≠ 0 := by
  contrapose! hpoly with h;
  -- By definition of analyticity on $\mathbb{C}$, the Taylor series of $f$ at 0 converges to $f$ everywhere.
  have h_taylor_series : ∀ z : ℂ, f z = ∑' n : ℕ, (iteratedDeriv n f 0 / Nat.factorial n) * z^n := by
    intro z;
    have := @Complex.taylorSeries_eq_on_ball;
    simpa [ div_eq_inv_mul, mul_assoc, mul_comm, mul_left_comm ] using Eq.symm ( this ( show DifferentiableOn ℂ f ( Metric.ball 0 ( ‖z‖ + 1 ) ) from hf.differentiableOn.mono <| Set.subset_univ _ ) <| show z ∈ Metric.ball 0 ( ‖z‖ + 1 ) from by simp );
  obtain ⟨ M, hM ⟩ := h; use ∑ n ∈ Finset.range ( M + 1 ), Polynomial.C ( iteratedDeriv n f 0 / ( n.factorial : ℂ ) ) * Polynomial.X ^ n; intro z; simp +decide [ h_taylor_series z, Polynomial.eval_finset_sum ] ; rw [ tsum_eq_sum ] ; aesop;

/-
For an everywhere convergent power series in x which is not merely a polynomial the central subscript v(x) tends to infinity with x.
-/
theorem problem_119 (f : ℂ → ℂ) (hf : AnalyticOn ℂ f ⊤)
    (hpoly : ¬∃ (p : Polynomial ℂ), ∀ z, f z = p.eval z) :
    ∀ M : ℕ, ∃ R : ℝ, ∀ (x : ℝ) (hx : R < |x|),
    let a : ℕ → ℂ := fun n => iteratedDeriv n f 0 / (n.factorial : ℂ)
    let terms : ℕ → ℝ := fun n => ‖a n * (x : ℂ) ^ n‖
    ∃ n > M, ∀ k, terms n ≥ terms k := by
      -- By the properties of the central subscript and the dominance of higher terms, we can find such an $R$.
      intro M
      obtain ⟨N, hN₁, hN₂⟩ : ∃ N > M, iteratedDeriv N f 0 ≠ 0 := by
        exact?;
      -- Since the series converges everywhere, the terms must tend to zero. Therefore, there exists some $n_{\text{max}}$ such that $|a_{n_{\text{max}}} x^{n_{\text{max}}}||$ is the largest among all terms.
      have h_max_exists : ∀ x : ℝ, ∃ n_max : ℕ, ∀ n : ℕ, ‖iteratedDeriv n f 0 / (n.factorial : ℂ) * x ^ n‖ ≤ ‖iteratedDeriv n_max f 0 / (n_max.factorial : ℂ) * x ^ n_max‖ := by
        -- Since the series converges everywhere, the terms must tend to zero. Therefore, there exists some $n_{\text{max}}$ such that $|a_{n_{\text{max}}} x^{n_{\text{max}}}||$ is the largest among all terms. Use the fact that a sequence of real numbers that tends to zero has a maximum.
        intro x
        have h_seq_zero : Filter.Tendsto (fun n : ℕ => ‖iteratedDeriv n f 0 / (n.factorial : ℂ) * x ^ n‖) Filter.atTop (nhds 0) := by
          have h_seq_zero : Summable (fun n : ℕ => ‖iteratedDeriv n f 0 / (n.factorial : ℂ) * x ^ n‖) := by
            -- Since $f$ is analytic on the entire complex plane, its Taylor series converges everywhere.
            have h_taylor_conv : ∀ z : ℂ, HasSum (fun n => iteratedDeriv n f 0 / (n.factorial : ℂ) * z ^ n) (f z) := by
              intro z
              have h_taylor_conv : AnalyticOn ℂ f ⊤ → ∀ z : ℂ, HasSum (fun n => iteratedDeriv n f 0 / (n.factorial : ℂ) * z ^ n) (f z) := by
                intro hf z
                have h_taylor_conv : ∀ z : ℂ, HasSum (fun n => iteratedDeriv n f 0 / (n.factorial : ℂ) * z ^ n) (f z) := by
                  have h_analytic : AnalyticOn ℂ f ⊤ := hf
                  intro z; exact (by
                  convert ( Complex.hasSum_taylorSeries_of_entire ( show ∀ z : ℂ, DifferentiableAt ℂ f z from fun z => h_analytic.differentiableOn.differentiableAt ( by simpa ) ) 0 z ) using 1 ; simp +decide [ div_eq_inv_mul, mul_assoc, mul_comm, mul_left_comm ])
                exact h_taylor_conv z
              exact h_taylor_conv hf z;
            exact Summable.norm ( h_taylor_conv x |> HasSum.summable );
          convert h_seq_zero.tendsto_atTop_zero;
        have h_seq_max : ∃ n_max ∈ Set.range (fun n : ℕ => ‖iteratedDeriv n f 0 / (n.factorial : ℂ) * x ^ n‖), ∀ n ∈ Set.range (fun n : ℕ => ‖iteratedDeriv n f 0 / (n.factorial : ℂ) * x ^ n‖), n_max ≥ n := by
          have h_seq_compact : IsCompact (Set.range (fun n : ℕ => ‖iteratedDeriv n f 0 / (n.factorial : ℂ) * x ^ n‖) ∪ {0}) := by
            have h_seq_compact : IsCompact (Set.range (fun n : ℕ => ‖iteratedDeriv n f 0 / (n.factorial : ℂ) * x ^ n‖) ∪ {0}) := by
              have h_seq_compact : IsCompact (Set.range (fun n : ℕ => ‖iteratedDeriv n f 0 / (n.factorial : ℂ) * x ^ n‖) ∪ {0}) := by
                have h_seq_compact : Filter.Tendsto (fun n : ℕ => ‖iteratedDeriv n f 0 / (n.factorial : ℂ) * x ^ n‖) Filter.atTop (nhds 0) := h_seq_zero
                simpa using h_seq_compact.isCompact_insert_range
              exact h_seq_compact;
            convert h_seq_compact using 1
          have := h_seq_compact.exists_isGreatest;
          simp_all +decide [ IsGreatest, mem_upperBounds ];
          exact this.elim ( fun h => ⟨ 0, fun n => le_trans ( h n ) ( by positivity ) ⟩ ) fun ⟨ n, hn₁, hn₂ ⟩ => ⟨ n, hn₂ ⟩;
        aesop;
      -- By the dominance of higher terms, for sufficiently large $|x|$, $|a_N x^N|$ will dominate all other terms $|a_k x^k|$ for $k \leq M$.
      obtain ⟨R, hR⟩ : ∃ R : ℝ, ∀ x : ℝ, abs x > R → ∀ k ≤ M, ‖iteratedDeriv k f 0 / (k.factorial : ℂ) * x ^ k‖ < ‖iteratedDeriv N f 0 / (N.factorial : ℂ) * x ^ N‖ := by
        have h_dominate : ∃ R : ℝ, ∀ x : ℝ, abs x > R → ∀ k ≤ M, ‖iteratedDeriv k f 0 / (k.factorial : ℂ)‖ * abs x ^ k < ‖iteratedDeriv N f 0 / (N.factorial : ℂ)‖ * abs x ^ N := by
          have h_dominate : ∃ R : ℝ, ∀ x : ℝ, abs x > R → ∀ k ≤ M, ‖iteratedDeriv k f 0 / (k.factorial : ℂ)‖ < ‖iteratedDeriv N f 0 / (N.factorial : ℂ)‖ * abs x ^ (N - k) := by
            have h_dominate : ∀ k ≤ M, ∃ R : ℝ, ∀ x : ℝ, abs x > R → ‖iteratedDeriv k f 0 / (k.factorial : ℂ)‖ < ‖iteratedDeriv N f 0 / (N.factorial : ℂ)‖ * abs x ^ (N - k) := by
              intro k hk
              have h_dominate : ∃ R : ℝ, ∀ x : ℝ, abs x > R → ‖iteratedDeriv k f 0 / (k.factorial : ℂ)‖ < ‖iteratedDeriv N f 0 / (N.factorial : ℂ)‖ * abs x := by
                exact ⟨ ‖iteratedDeriv k f 0 / ( k.factorial : ℂ )‖ / ‖iteratedDeriv N f 0 / ( N.factorial : ℂ )‖ + 1, fun x hx => by nlinarith [ abs_nonneg x, show 0 < ‖iteratedDeriv N f 0 / ( N.factorial : ℂ )‖ from norm_pos_iff.mpr ( div_ne_zero hN₂ <| Nat.cast_ne_zero.mpr <| Nat.factorial_ne_zero _ ), mul_div_cancel₀ ‖iteratedDeriv k f 0 / ( k.factorial : ℂ )‖ <| show ‖iteratedDeriv N f 0 / ( N.factorial : ℂ )‖ ≠ 0 from norm_ne_zero_iff.mpr <| div_ne_zero hN₂ <| Nat.cast_ne_zero.mpr <| Nat.factorial_ne_zero _ ] ⟩;
              exact ⟨ Max.max h_dominate.choose 1, fun x hx => lt_of_lt_of_le ( h_dominate.choose_spec x ( lt_of_le_of_lt ( le_max_left _ _ ) hx ) ) ( mul_le_mul_of_nonneg_left ( le_self_pow₀ ( by linarith [ le_max_right h_dominate.choose 1, abs_nonneg x ] ) ( Nat.sub_ne_zero_of_lt ( by linarith ) ) ) ( norm_nonneg _ ) ) ⟩;
            choose! R hR using h_dominate;
            exact ⟨ ∑ k ∈ Finset.range ( M + 1 ), |R k|, fun x hx k hk => hR k hk x <| lt_of_le_of_lt ( Finset.single_le_sum ( fun a _ => abs_nonneg ( R a ) ) ( Finset.mem_range.mpr <| Nat.lt_succ_of_le hk ) |> le_trans ( le_abs_self _ ) ) hx ⟩;
          obtain ⟨ R, hR ⟩ := h_dominate; use Max.max R 1; intro x hx k hk; specialize hR x ( lt_of_le_of_lt ( le_max_left _ _ ) hx ) k hk; rw [ show |x| ^ N = |x| ^ ( N - k ) * |x| ^ k by rw [ ← pow_add, Nat.sub_add_cancel ( by linarith ) ] ] ; nlinarith [ pow_pos ( show 0 < |x| by linarith [ le_max_right R 1 ] ) k ] ;
        aesop;
      exact ⟨ R, fun x hx => by obtain ⟨ n_max, hn_max ⟩ := h_max_exists x; exact ⟨ n_max, not_le.mp fun contra => not_le_of_gt ( hR x hx n_max contra ) ( by simpa [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm ] using hn_max N ), fun k => by simpa [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm ] using hn_max k ⟩ ⟩