/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: bd872c44-7916-477d-b008-cf32dc4763c7

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Real
open Set
open Filter

#check intervalIntegral

#check (⨅ x ∈ Set.Icc (0:ℝ) 1, x)

#check MeasureTheory.volume

#check nhds

#check sInf

#check sSup

/-
If p_n(x,t) is a non-negative kernel with integral 1, and f is continuous, then the integral transform f_n(x) = ∫ p_n(x,t) f(t) dt is bounded by the minimum and maximum of f on [a,b].
-/
lemma problem_132_part1 {a b : ℝ} (hab : a < b) (f : ℝ → ℝ) (hf : ContinuousOn f (Set.Icc a b))
    (p : ℕ → ℝ → ℝ → ℝ) (hp_cont : ∀ n, ContinuousOn (λ (x,t) ↦ p n x t) ((Set.Icc a b) ×ˢ (Set.Icc a b)))
    (hp_nonneg : ∀ n x t, a ≤ x → x ≤ b → a ≤ t → t ≤ b → 0 ≤ p n x t)
    (hp_integral_one : ∀ n x, a ≤ x → x ≤ b →
        intervalIntegral (λ t ↦ p n x t) a b MeasureTheory.volume = 1) :
    (∀ (n : ℕ) (x : ℝ) (hx : x ∈ Set.Icc a b),
        sInf (f '' (Set.Icc a b)) ≤ intervalIntegral (λ t ↦ p n x t * f t) a b MeasureTheory.volume ∧
        intervalIntegral (λ t ↦ p n x t * f t) a b MeasureTheory.volume ≤ sSup (f '' (Set.Icc a b))) := by
  norm_num +zetaDelta at *;
  intro n x hx₁ hx₂; rw [ intervalIntegral.integral_of_le hab.le ];
  constructor;
  · refine' le_trans _ ( MeasureTheory.setIntegral_mono_on _ _ measurableSet_Ioc fun t ht => mul_le_mul_of_nonneg_left ( show f t ≥ InfSet.sInf ( f '' Set.Icc a b ) by exact ( csInf_le ( IsCompact.bddBelow <| isCompact_Icc.image_of_continuousOn hf ) <| Set.mem_image_of_mem _ <| Set.Ioc_subset_Icc_self ht ) ) <| hp_nonneg n x t hx₁ hx₂ ht.1.le ht.2 );
    · rw [ MeasureTheory.integral_mul_const ] ; rw [ ← intervalIntegral.integral_of_le hab.le ] ; aesop;
    · have h_integrable : MeasureTheory.IntegrableOn (fun t => p n x t) (Set.Ioc a b) := by
        have := hp_integral_one n x hx₁ hx₂;
        exact ( by rw [ intervalIntegral.integral_of_le hab.le ] at this; exact ( by contrapose! this; rw [ MeasureTheory.integral_undef this ] ; norm_num ) );
      exact h_integrable.mul_const _;
    · have h_integrable : MeasureTheory.IntegrableOn (fun t => p n x t) (Set.Ioc a b) := by
        have := hp_integral_one n x hx₁ hx₂;
        exact ( by rw [ intervalIntegral.integral_of_le hab.le ] at this; exact ( by contrapose! this; rw [ MeasureTheory.integral_undef this ] ; norm_num ) );
      refine' MeasureTheory.Integrable.mono' _ _ _;
      refine' fun t => p n x t * ( SupSet.sSup ( Set.image ( fun t => |f t| ) ( Set.Icc a b ) ) );
      · exact h_integrable.mul_const _;
      · exact MeasureTheory.AEStronglyMeasurable.mul ( h_integrable.aestronglyMeasurable ) ( hf.aestronglyMeasurable ( measurableSet_Icc ) |> fun h => h.mono_set <| Set.Ioc_subset_Icc_self );
      · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with t ht using by rw [ Real.norm_eq_abs, abs_mul, abs_of_nonneg ( hp_nonneg n x t hx₁ hx₂ ht.1.le ht.2 ) ] ; exact mul_le_mul_of_nonneg_left ( le_csSup ( IsCompact.bddAbove ( isCompact_Icc.image_of_continuousOn ( continuous_abs.comp_continuousOn hf ) ) ) ( Set.mem_image_of_mem _ <| Set.Ioc_subset_Icc_self ht ) ) ( hp_nonneg n x t hx₁ hx₂ ht.1.le ht.2 ) ;
  · refine' le_trans ( MeasureTheory.setIntegral_mono_on _ _ measurableSet_Ioc fun t ht => mul_le_mul_of_nonneg_left ( show f t ≤ SupSet.sSup ( f '' Set.Icc a b ) from le_csSup ( IsCompact.bddAbove ( isCompact_Icc.image_of_continuousOn hf ) ) <| Set.mem_image_of_mem _ <| Set.Ioc_subset_Icc_self ht ) <| hp_nonneg n x t hx₁ hx₂ ht.1.le ht.2 ) _;
    · have h_integrable : MeasureTheory.IntegrableOn (fun t => p n x t) (Set.Icc a b) := by
        have := hp_cont n;
        exact ContinuousOn.integrableOn_Icc ( this.comp ( continuousOn_const.prodMk continuousOn_id ) fun t ht => by aesop );
      refine' MeasureTheory.Integrable.mono' _ _ _;
      refine' fun t => |p n x t| * ( SupSet.sSup ( Set.image ( fun t => |f t| ) ( Set.Icc a b ) ) );
      · exact MeasureTheory.Integrable.mul_const ( h_integrable.abs.mono_measure <| MeasureTheory.Measure.restrict_mono Set.Ioc_subset_Icc_self le_rfl ) _;
      · exact MeasureTheory.AEStronglyMeasurable.mul ( h_integrable.aestronglyMeasurable.mono_set <| Set.Ioc_subset_Icc_self ) ( hf.aestronglyMeasurable measurableSet_Icc |> fun h => h.mono_set <| Set.Ioc_subset_Icc_self );
      · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with t ht using by rw [ norm_mul ] ; exact mul_le_mul_of_nonneg_left ( le_csSup ( IsCompact.bddAbove ( isCompact_Icc.image_of_continuousOn ( continuous_abs.comp_continuousOn hf ) ) ) ( Set.mem_image_of_mem _ <| Set.Ioc_subset_Icc_self ht ) ) ( abs_nonneg _ ) ;
    · refine' MeasureTheory.Integrable.mul_const _ _;
      exact ( by have := hp_integral_one n x hx₁ hx₂; exact ( by rw [ intervalIntegral.integral_of_le hab.le ] at this; exact ( by contrapose! this; rw [ MeasureTheory.integral_undef this ] ; norm_num ) ) );
    · rw [ MeasureTheory.integral_mul_const, ← intervalIntegral.integral_of_le hab.le ] ; aesop

/-
The integral of p_n(x,t) * |f(t) - f(x)| over [x-δ, x+δ] is at most ε, provided |f(t) - f(x)| ≤ ε on that interval.
-/
lemma problem_132_near_region {a b : ℝ} (hab : a < b) (f : ℝ → ℝ) (hf : ContinuousOn f (Set.Icc a b))
    (p : ℕ → ℝ → ℝ → ℝ) (hp_cont : ∀ n, ContinuousOn (λ (x,t) ↦ p n x t) ((Set.Icc a b) ×ˢ (Set.Icc a b)))
    (hp_nonneg : ∀ n x t, a ≤ x → x ≤ b → a ≤ t → t ≤ b → 0 ≤ p n x t)
    (hp_integral_one : ∀ n x, a ≤ x → x ≤ b →
        intervalIntegral (λ t ↦ p n x t) a b MeasureTheory.volume = 1)
    (x : ℝ) (hx : a < x ∧ x < b) (ε : ℝ) (hε : 0 < ε) (δ : ℝ) (hδ : 0 < δ) (hδ_small : a ≤ x - δ ∧ x + δ ≤ b)
    (hf_near : ∀ t ∈ Set.Icc (x - δ) (x + δ), |f t - f x| ≤ ε) :
    ∀ n, intervalIntegral (λ t ↦ p n x t * |f t - f x|) (x - δ) (x + δ) MeasureTheory.volume ≤ ε := by
      intro n
      have h_integrable : MeasureTheory.IntegrableOn (fun t => p n x t) (Set.Icc (x - δ) (x + δ)) := by
        have h_integrable : MeasureTheory.IntegrableOn (fun t => p n x t) (Set.Icc a b) := by
          have := hp_cont n;
          exact ContinuousOn.integrableOn_Icc ( this.comp ( continuousOn_const.prodMk continuousOn_id ) fun t ht => ⟨ ⟨ by linarith [ ht.1 ], by linarith [ ht.2 ] ⟩, ht ⟩ );
        exact h_integrable.mono_set <| Set.Icc_subset_Icc ( by linarith ) ( by linarith );
      -- Using the fact that $|f(t) - f(x)| \leq \epsilon$ on $[x - \delta, x + \delta]$, we can bound the integral.
      have h_bound : ∫ t in (x - δ)..x + δ, p n x t * |f t - f x| ≤ ∫ t in (x - δ)..x + δ, p n x t * ε := by
        apply_rules [ intervalIntegral.integral_mono_on ];
        · linarith;
        · rw [ intervalIntegrable_iff_integrableOn_Icc_of_le ( by linarith ) ];
          refine' MeasureTheory.Integrable.mono' _ _ _;
          refine' fun t => p n x t * ε;
          · exact h_integrable.mul_const _;
          · exact MeasureTheory.AEStronglyMeasurable.mul ( h_integrable.aestronglyMeasurable ) ( ContinuousOn.aestronglyMeasurable ( by exact ContinuousOn.abs ( hf.sub continuousOn_const |> ContinuousOn.mono <| Set.Icc_subset_Icc ( by linarith ) ( by linarith ) ) ) measurableSet_Icc );
          · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with t ht using by rw [ Real.norm_eq_abs, abs_of_nonneg ( mul_nonneg ( hp_nonneg n x t ( by linarith ) ( by linarith ) ( by linarith [ ht.1 ] ) ( by linarith [ ht.2 ] ) ) ( abs_nonneg _ ) ) ] ; exact mul_le_mul_of_nonneg_left ( hf_near t ht ) ( hp_nonneg n x t ( by linarith ) ( by linarith ) ( by linarith [ ht.1 ] ) ( by linarith [ ht.2 ] ) ) ;
        · rw [ intervalIntegrable_iff_integrableOn_Icc_of_le ( by linarith ) ] ; exact h_integrable.mul_const _;
        · exact fun t ht => mul_le_mul_of_nonneg_left ( hf_near t ht ) ( hp_nonneg n x t ( by linarith ) ( by linarith ) ( by linarith [ ht.1 ] ) ( by linarith [ ht.2 ] ) );
      -- Since $\int_{x-\delta}^{x+\delta} p_n(x,t) \, dt \leq 1$, we have $\int_{x-\delta}^{x+\delta} p_n(x,t) \, dt * \epsilon \leq \epsilon$.
      have h_integral_le_one : ∫ t in (x - δ)..x + δ, p n x t ≤ 1 := by
        rw [ ← hp_integral_one n x ( by linarith ) ( by linarith ) ];
        apply_rules [ intervalIntegral.integral_mono_interval ] <;> try linarith;
        · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with t ht using hp_nonneg n x t ( by linarith [ ht.1 ] ) ( by linarith [ ht.2 ] ) ( by linarith [ ht.1 ] ) ( by linarith [ ht.2 ] );
        · rw [ intervalIntegrable_iff_integrableOn_Icc_of_le ( by linarith ) ];
          have := hp_cont n;
          exact ContinuousOn.integrableOn_Icc ( this.comp ( continuousOn_const.prodMk continuousOn_id ) fun x hx => ⟨ ⟨ by linarith [ hx.1 ], by linarith [ hx.2 ] ⟩, hx ⟩ );
      exact h_bound.trans ( by rw [ intervalIntegral.integral_mul_const ] ; nlinarith )

/-
The integral of p_n(x,t) * |f(t) - f(x)| over [x-δ, x+δ] is at most ε, provided |f(t) - f(x)| ≤ ε on that interval.
-/
lemma problem_132_near_region_v2 {a b : ℝ} (hab : a < b) (f : ℝ → ℝ) (hf : ContinuousOn f (Set.Icc a b))
    (p : ℕ → ℝ → ℝ → ℝ) (hp_cont : ∀ n, ContinuousOn (λ (x,t) ↦ p n x t) ((Set.Icc a b) ×ˢ (Set.Icc a b)))
    (hp_nonneg : ∀ n x t, a ≤ x → x ≤ b → a ≤ t → t ≤ b → 0 ≤ p n x t)
    (hp_integral_one : ∀ n x, a ≤ x → x ≤ b →
        intervalIntegral (λ t ↦ p n x t) a b MeasureTheory.volume = 1)
    (x : ℝ) (hx : a < x ∧ x < b) (ε : ℝ) (hε : 0 < ε) (δ : ℝ) (hδ : 0 < δ) (hδ_small : a ≤ x - δ ∧ x + δ ≤ b)
    (hf_near : ∀ t ∈ Set.Icc (x - δ) (x + δ), |f t - f x| ≤ ε) :
    ∀ n, intervalIntegral (λ t ↦ p n x t * |f t - f x|) (x - δ) (x + δ) MeasureTheory.volume ≤ ε := by
      -- Apply the provided lemma to get the bound.
      intros n
      apply le_trans (problem_132_near_region hab f hf p hp_cont hp_nonneg hp_integral_one x hx ε hε δ hδ hδ_small hf_near n) (by norm_num)

/-
If p is non-negative and |f(t) - f(x)| ≤ M on [u, v], then ∫_u^v p(t) |f(t) - f(x)| dt ≤ M * ∫_u^v p(t) dt.
-/
lemma integral_bound_interval {u v : ℝ} (huv : u ≤ v) (p : ℝ → ℝ) (f : ℝ → ℝ) (x M : ℝ)
  (hp_cont : ContinuousOn p (Set.Icc u v))
  (hf_cont : ContinuousOn f (Set.Icc u v))
  (hp_nonneg : ∀ t ∈ Set.Icc u v, 0 ≤ p t)
  (hf_bound : ∀ t ∈ Set.Icc u v, |f t - f x| ≤ M) :
  intervalIntegral (λ t ↦ p t * |f t - f x|) u v MeasureTheory.volume ≤ M * intervalIntegral p u v MeasureTheory.volume := by
    rw [ intervalIntegral.integral_of_le huv, intervalIntegral.integral_of_le huv ];
    rw [ ←MeasureTheory.integral_const_mul ] ; exact MeasureTheory.setIntegral_mono_on ( by exact ContinuousOn.integrableOn_Icc ( by exact ContinuousOn.mul hp_cont ( ContinuousOn.abs ( hf_cont.sub continuousOn_const ) ) ) |> fun h => h.mono_set <| Set.Ioc_subset_Icc_self ) ( by exact ContinuousOn.integrableOn_Icc ( by exact ContinuousOn.mul continuousOn_const hp_cont ) |> fun h => h.mono_set <| Set.Ioc_subset_Icc_self ) measurableSet_Ioc fun t ht => by nlinarith [ hf_bound t <| Set.Ioc_subset_Icc_self ht, hp_nonneg t <| Set.Ioc_subset_Icc_self ht ] ;

/-
The integral of p_n(x,t) * |f(t) - f(x)| over [a, x-δ] is bounded by M * integral of p_n(x,t) over [a, x-δ].
-/
lemma problem_132_far_region_bound_left {a b : ℝ} (hab : a < b) (f : ℝ → ℝ) (hf : ContinuousOn f (Set.Icc a b))
    (p : ℕ → ℝ → ℝ → ℝ) (hp_cont : ∀ n, ContinuousOn (λ (x,t) ↦ p n x t) ((Set.Icc a b) ×ˢ (Set.Icc a b)))
    (hp_nonneg : ∀ n x t, a ≤ x → x ≤ b → a ≤ t → t ≤ b → 0 ≤ p n x t)
    (x : ℝ) (hx : a < x ∧ x < b) (δ : ℝ) (hδ : 0 < δ) (hδ_small : a ≤ x - δ ∧ x + δ ≤ b)
    (M : ℝ) (hM : ∀ t ∈ Set.Icc a b, |f t - f x| ≤ M) :
    ∀ n, intervalIntegral (λ t ↦ p n x t * |f t - f x|) a (x - δ) MeasureTheory.volume ≤ M * intervalIntegral (λ t ↦ p n x t) a (x - δ) MeasureTheory.volume := by
      -- Apply the function `integral_bound_interval` to the interval [a, x-δ] and use the fact that |f t - f x| ≤ M for all t in this interval.
      intros n
      have h_apply_integral_bound : ∀ t ∈ Set.Icc a (x - δ), |f t - f x| ≤ M := by
        exact fun t ht => hM t ⟨ ht.1, by linarith [ ht.2 ] ⟩;
      -- Apply the lemma `integral_bound_interval` to the interval [a, x-δ].
      have := integral_bound_interval (by linarith : a ≤ x - δ) (fun t => p n x t) (fun t => f t) x M (by
      -- Since $p n$ is continuous on the product set $[a, b] \times [a, b]$, and $x \in [a, b]$, the function $t \mapsto p n x t$ is continuous on $[a, x - \delta]$.
      have h_cont : ContinuousOn (fun t => p n x t) (Set.Icc a b) := by
        have := hp_cont n;
        exact this.comp ( continuousOn_const.prodMk continuousOn_id ) fun t ht => ⟨ ⟨ by linarith [ ht.1 ], by linarith [ ht.2 ] ⟩, ht ⟩;
      exact h_cont.mono <| Set.Icc_subset_Icc_right <| by linarith;) (by
      exact hf.mono ( Set.Icc_subset_Icc le_rfl ( by linarith ) )) (by
      exact fun t ht => hp_nonneg n x t ( by linarith [ ht.1 ] ) ( by linarith [ ht.2 ] ) ( by linarith [ ht.1 ] ) ( by linarith [ ht.2 ] )) (by
      exact h_apply_integral_bound) ; aesop

/-
The integral of p_n(x,t) * |f(t) - f(x)| over [x+δ, b] is bounded by M * integral of p_n(x,t) over [x+δ, b].
-/
lemma problem_132_far_region_bound_right {a b : ℝ} (hab : a < b) (f : ℝ → ℝ) (hf : ContinuousOn f (Set.Icc a b))
    (p : ℕ → ℝ → ℝ → ℝ) (hp_cont : ∀ n, ContinuousOn (λ (x,t) ↦ p n x t) ((Set.Icc a b) ×ˢ (Set.Icc a b)))
    (hp_nonneg : ∀ n x t, a ≤ x → x ≤ b → a ≤ t → t ≤ b → 0 ≤ p n x t)
    (x : ℝ) (hx : a < x ∧ x < b) (δ : ℝ) (hδ : 0 < δ) (hδ_small : a ≤ x - δ ∧ x + δ ≤ b)
    (M : ℝ) (hM : ∀ t ∈ Set.Icc a b, |f t - f x| ≤ M) :
    ∀ n, intervalIntegral (λ t ↦ p n x t * |f t - f x|) (x + δ) b MeasureTheory.volume ≤ M * intervalIntegral (λ t ↦ p n x t) (x + δ) b MeasureTheory.volume := by
      -- We apply `integral_bound_interval` to the interval [x+δ, b].
      intro n
      have := integral_bound_interval (by linarith : x + δ ≤ b) (fun t => p n x t) (fun t => f t) x M
      generalize_proofs at *;
      apply this;
      · have := hp_cont n;
        have := this.comp ( show ContinuousOn ( fun t => ( x, t ) ) ( Set.Icc ( x + δ ) b ) from continuousOn_const.prodMk continuousOn_id ) ( fun t ht => by constructor <;> constructor <;> linarith [ ht.1, ht.2 ] ) ; aesop;
      · exact hf.mono ( Set.Icc_subset_Icc ( by linarith ) le_rfl );
      · exact fun t ht => hp_nonneg n x t ( by linarith ) ( by linarith ) ( by linarith [ ht.1 ] ) ( by linarith [ ht.2 ] );
      · exact fun t ht => hM t ⟨ by linarith [ ht.1 ], by linarith [ ht.2 ] ⟩

/-
The integral of p_n(x,t) * |f(t) - f(x)| over [x+δ, b] is bounded by M * integral of p_n(x,t) over [x+δ, b].
-/
lemma problem_132_far_region_bound_right_v2 {a b : ℝ} (hab : a < b) (f : ℝ → ℝ) (hf : ContinuousOn f (Set.Icc a b))
    (p : ℕ → ℝ → ℝ → ℝ) (hp_cont : ∀ n, ContinuousOn (λ (x,t) ↦ p n x t) ((Set.Icc a b) ×ˢ (Set.Icc a b)))
    (hp_nonneg : ∀ n x t, a ≤ x → x ≤ b → a ≤ t → t ≤ b → 0 ≤ p n x t)
    (x : ℝ) (hx : a < x ∧ x < b) (δ : ℝ) (hδ : 0 < δ) (hδ_small : a ≤ x - δ ∧ x + δ ≤ b)
    (M : ℝ) (hM : ∀ t ∈ Set.Icc a b, |f t - f x| ≤ M) :
    ∀ n, intervalIntegral (λ t ↦ p n x t * |f t - f x|) (x + δ) b MeasureTheory.volume ≤ M * intervalIntegral (λ t ↦ p n x t) (x + δ) b MeasureTheory.volume := by
      -- Applying the lemma `integral_bound_interval` to the interval [x+δ, b].
      intros n
      apply problem_132_far_region_bound_right hab f hf p hp_cont hp_nonneg x hx δ hδ hδ_small M hM n

/-
The integral of p_n(x,t) * |f(t) - f(x)| over the far region is bounded by M times the integral of p_n(x,t) over the far region.
-/
lemma problem_132_far_region_bound {a b : ℝ} (hab : a < b) (f : ℝ → ℝ) (hf : ContinuousOn f (Set.Icc a b)) 
    (p : ℕ → ℝ → ℝ → ℝ) (hp_cont : ∀ n, ContinuousOn (λ (x,t) ↦ p n x t) ((Set.Icc a b) ×ˢ (Set.Icc a b)))
    (hp_nonneg : ∀ n x t, a ≤ x → x ≤ b → a ≤ t → t ≤ b → 0 ≤ p n x t)
    (x : ℝ) (hx : a < x ∧ x < b) (δ : ℝ) (hδ : 0 < δ) (hδ_small : a ≤ x - δ ∧ x + δ ≤ b)
    (M : ℝ) (hM : ∀ t ∈ Set.Icc a b, |f t - f x| ≤ M) :
    ∀ n, (intervalIntegral (λ t ↦ p n x t * |f t - f x|) a (x - δ) MeasureTheory.volume) + (intervalIntegral (λ t ↦ p n x t * |f t - f x|) (x + δ) b MeasureTheory.volume) ≤ M * ((intervalIntegral (λ t ↦ p n x t) a (x - δ) MeasureTheory.volume) + (intervalIntegral (λ t ↦ p n x t) (x + δ) b MeasureTheory.volume)) := by
  intro n
  rw [mul_add]
  apply add_le_add
  · apply problem_132_far_region_bound_left hab f hf p hp_cont hp_nonneg x hx δ hδ hδ_small M hM
  · apply problem_132_far_region_bound_right_v2 hab f hf p hp_cont hp_nonneg x hx δ hδ hδ_small M hM