/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d740ea5f-7293-443b-911f-a70e38947c28
-/

/-
We formalized and proved the statement from Polya-Szego Problem 127 regarding the bounds of integrals with non-negative weight functions. Specifically, we showed that if $p_n$ are non-negative continuous functions on $[a, b]$ with $\int_a^b p_n(t) dt = 1$, and $f$ is continuous on $[a, b]$, then $\int_a^b p_n(t) f(t) dt$ lies between the minimum and maximum values of $f$ on $[a, b]$. The proof utilizes the monotonicity of the integral and the fact that $f$ is bounded on the compact interval $[a, b]$.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Given a sequence of continuous non-negative functions p_n with integral 1 on [a, b], and a continuous function f, the integral of p_n * f is between the minimum and maximum of f on [a, b].
-/
theorem integral_between_min_max {a b : ℝ} (hab : a ≤ b)
    {p : ℕ → ℝ → ℝ} (hp_cont : ∀ n, ContinuousOn (p n) (Set.uIcc a b))
    (hp_nonneg : ∀ n t, t ∈ Set.uIcc a b → p n t ≥ 0)
    (hp_int_one : ∀ n, ∫ t in a..b, p n t = 1)
    {f : ℝ → ℝ} (hf_cont : ContinuousOn f (Set.uIcc a b)) (n : ℕ) :
    sInf (f '' Set.uIcc a b) ≤ ∫ t in a..b, p n t * f t ∧
    ∫ t in a..b, p n t * f t ≤ sSup (f '' Set.uIcc a b) := by
      constructor;
      · -- By definition of integrals, we know that
        have h_int_le : ∫ t in a..b, p n t * f t ≥ ∫ t in a..b, p n t * (sInf (f '' Set.uIcc a b)) := by
          apply_rules [ intervalIntegral.integral_mono_on ];
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            exact ContinuousOn.mul ( hp_cont n ) continuousOn_const;
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            exact ContinuousOn.mul ( hp_cont n ) hf_cont;
          · exact fun x hx => mul_le_mul_of_nonneg_left ( csInf_le ( IsCompact.bddBelow <| isCompact_Icc.image_of_continuousOn <| hf_cont.mono <| by aesop_cat ) <| Set.mem_image_of_mem _ <| by aesop_cat ) <| hp_nonneg n x <| by aesop_cat;
        simp_all +decide [ intervalIntegral.integral_comp_mul_right ];
      · -- Using the fact that $p_n(t) \geq 0$ and $\int_a^b p_n(t) \, dt = 1$, we can bound the integral of $p_n(t) * f(t)$.
        have h_bound : ∫ t in a..b, p n t * f t ≤ ∫ t in a..b, p n t * (sSup (f '' Set.uIcc a b)) := by
          apply_rules [ intervalIntegral.integral_mono_on ];
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            exact ContinuousOn.mul ( hp_cont n ) hf_cont;
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            exact ContinuousOn.mul ( hp_cont n ) continuousOn_const;
          · exact fun x hx => mul_le_mul_of_nonneg_left ( le_csSup ( by exact IsCompact.bddAbove ( isCompact_uIcc.image_of_continuousOn hf_cont ) ) ( Set.mem_image_of_mem f <| by simpa [ hab ] using hx ) ) ( hp_nonneg n x <| by simpa [ hab ] using hx );
        aesop